apiVersion: v1
stringData:
  values.yaml: ENC[AES256_GCM,data:m07AWLuw3ABv/SImhQ7XwSGpiPFkwSt4A0iljK0cRbVYcxBXnNQyH+t2v43SciZZKHlFBGqO+MgvSipbrX8gqQ4+ZFy68xaebzanunU/wix8VPbtsCPkernMe8Rzb6wuUR6O29pp6Xv0EIq5RHjATkbSBDFEQcnSsKNPlnuEjIYm9mVGcgs4+fq5P6/7JVrxTk0Dew==,iv:IJAVChQlYrgM43CW0Dm+CHMRFU8NmUeDGfzwLycQTyA=,tag:svQglXuRFP6GVwojSuZEcg==,type:str]
kind: Secret
metadata:
  name: tailscale-config
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFKMnliMkpX
        WFpiMjduaWlmbEIzNUo3T3NLREFDRDRJVy82UUl2Q3dYNkNyZytUVjRqVHJWek9Y
        SkhzNUtXNnphM3VVYm1QOGN3RVdSb1dta0wyQllyemVOc2xjUEtnTmFRUVRsZUFm
        cmZBZi85WFY0bHJvYXpEbCt4TERnci9CRld1bUpqaXpSdzI1ZjFTa3VXR1FZV2tQ
        elAyQzdXWEpEbFBrRVkwR1A1blg5dUpwbHpsKzlXNzEyUy9rb0ltMHk2S2dRRWVm
        K2traDkxL3ZnbmpTc1dpSGs5WXllSnBVUXZZRjdteklLLzRNbis0aEdIMnNUMVh4
        L1pqeWpyUTRvK1YxZU1FV3FrNG5rOExoTldzWTdSdlM3NEVjeUhsZGUrNmZITXVh
        dXVQN29ZOGtDMWtxVEF0RzZKVW1OK3ZNWDVQaGtSTSt6UHBvVzI3cW5TK1A4Zmxs
        OU1PckI0Y0ZpMDdIdHpnNUhQMzc2OWUvZStKZG1pNEVMdWE5NkRBVU85T0t1Vjcv
        VDRLVFZDR09WMlF5VmlxMS8vaFM3dHcxKzNQdWY1eUNRZEFCNDVnbWNBdkFHOHRo
        ZGVSZHFLRkx4OWY0dWVtRjdnZlNybk56cGZIUkE0ZkJWd3V3Skx0elNqSEVMVlVG
        ZTI4eDFGYkQyeTdrTUtHdTV5V1FvTXcwSDB3ZVZuSVhnRW1LVlIrN3Q0bHJJOFZj
        cXRsN21uT3grM2s3V1h3cENjTG1pQlBIblcxdDBIK3p6aXVyOWNQL0JFay9rUTRo
        UmpPb1lqZkdad0U1TUFWbHdQSllYeE1YUXc2NFNHU25EYm9QQWRJSkViaHVJT0VF
        eHdwUmF4NGUrbnRHL2U3ZzRHTThpbkUxejc0bHNsaEFYZWEwOWxvNFp6eW9ZNERP
        aW1pWVVEU00rTzFIQW9wOHE0VlhNT1EwMUZwNnpKQnQ3dmdoNU5YZmljOVpZcHpQ
        Q1JTNWl2UkdEY1B3dWNyaTlMV21YOFFWNENFR1lTTThZWW5KaFFjOTl2cHBWNlFw
        VitqQWVaOHFtWXVBTGhjT0xDSGxCRG0rSGdvdHg3VXArTldWaUQ3aXQzRTFYSi9O
        ZTZvRUJCTEtWNllJQ3gzM2JaR3l0T2RRcWdXeFNhQ1VYYmpjN1J5cXVza2dCTkJZ
        ak95em05ZUJ6cXU0UG9PY0t1bjI1U0o0eUh6ZUJCSndFMmxoS1g3NndSTHd4L3Rk
        RGlOcGRRSktiRllEOGVSQ0hvdkFSOFFtSWVlUFVTbGJJMjdYY1RpdDQxYnVvVGkz
        NTFRdnR5SnV4MXVJdHdnN1R1aXd6UXYzL2hVWG5XUlk2WGloeXloR1BPUEIvMjdR
        QTZiN2hLMGQ1S000bjAyVDZIM3VyUCtwTFl1QncwRmM5V2s4NEh3SndwMDBGSTJI
        M3FrTWdJZHRDeXQvdkRnemhpM1VGU3JNT3hZK1lDVDQ5RU9IU1h1QWZZQWdXRFZt
        eG9HQ2U1OENxeW1kMHdhM0g4QjhJZzkxSVY4SmZ4UXZhVGliYU0vZG9YZ3BxOS9R
        QkFXaktHQjR2VlNLdWdWTlYzRFZSK2FsdVZQUWk2eTEwM2Q1K2JtYlcrOW03ZUlp
        Z045S0Uxc1dwYml2Mm5ueCtMencvVVNJYTFnbGJQdFd2b25BdkJadnNuSnpyd2M4
        d044dWhNc2IwSTB1aXMwK0dRYVFPWFVtVTlBRDhxdjNHbWkrVThlYUxIT1RlSzI1
        dzl5QXZQMmhkOW5lakhYQktRUERFeGwyQkp5THoxUUtLTFhFWVBSbmRlRmJkRitX
        SWw0QXl3dkRxTDBxUkgrRHZLU1EwYWdBMkRzWXpBMnNOelNTb3VPUUJ1bFdWR2hn
        dEpNOXVSWVVZRHgrMVpzeWRiU3dmWEY2UEdwUlZiUG1kZG5CS3g4ODNMbzV2UHpU
        dXM0QjM0UytIdjJTSG43VjBVaUkreHV4UDBndEpqaEd0bVlDSkRPTnVmZk5BUQpK
        dGNmd2lETWJlMkVXVEtrWlVXWjh4SW9scS84LzkvaGdSc2VoM1RRRGtjCi0tLSBv
        enppQmRnRGRIUFZRRmtrVWdNaGRXa3ltL1o5R0V1MXZPMFY2Sk1zQVFnCoRBYWWl
        2J5hhkKcvFQKhYSWT9Ab7JbqoDiyio+iEotS6v6Viw/RtZMhSW1JdZHZmiU61bgT
        l0vw/2ZWjbpcjow=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:F6lQNmwfMg5eUI1B8U94gSFl/FezeMu4Lh5sC63o5doKRatNG3TRHiBNzTGGzZeAQCUzEB5xV+vADTtqG7k+2xq+ArO55S4zH+DOoHiOe/oGqBVBOLpK7MOkXsY4oSgh3wNnr1fN9VhP0vabz1KDQpzHNHzSpL34zIRGZl/k90c=,iv:xeiLsQZUceWg3soV0m8CWjWz4cHfnQzTTtIQebQXOwU=,tag:y9ZAC4NKTCj5jKNHMBbM3Q==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.10.2
