apiVersion: v1
data:
  IPINFO_TOKEN: ENC[AES256_GCM,data:Oahp4jsj4ry9VA/QetnVw9rAuJ8=,iv:1+Cb9MeE/JFgxpB7zZsfrKjGWprMo5T4zsr9k4KydQc=,tag:Anh3EiFskv+dzUKhykjkHg==,type:str]
kind: Secret
metadata:
  name: iplookup-secret
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDlzK0JKUStv
        YWg1VFpkQnNQcUE3NGdvQTUwQTdvbHJVSXNVUmhEczF6MTBDMU9YTUoxdHVQZjkv
        c3VESGVPelBqOW8wTFJQZGV1dkdxZVNvdWRxUkhlN2tTQk9WVGlrczFDUFF5OWlD
        ZmwvNGFvUVpWZVRIWEVnOHVDY2FINjFNQmRRa3NQOFFRaTJkRVdoR2RrOTBZLzFS
        ZmV0TlRGa0dzL2h3QzZJSnFMRldyZndKajdVRWd0Q3ZONFAvajZyUlBQaTRjVDNC
        RC9ZY3MyMzBFYzBVY1ZFSzhMRmhmL0tSZUZIVXRXZW5uc2xLVWFEN0Y2WitFWjZC
        ajBZcy9KRGxoUXR6YzFqM2IxYnVjRjMvSHQ2Z1IxWURHTWFsaVRQZXdCL0NDZXdT
        YTltQlFZSVFXd0wzUnZyRTZSZFNtZzRQa3NVVE9zdGtGcWpVRWpWMVJLTWY3c0g1
        amRaVHZ2MWl6SXpDb1k0YWpheERFWEVzTU8rSDY0dU10cXc3L3RvZUhCemd2b0Zm
        VWIwYUZneS9xR0xHUVFBKzV6Vk1BZ2FjSUlGNWVrVjBRVll1SkhaZys1dlBXRUhD
        QjIyM1lXM01QcEpERzFzNUpDNDM0MENIZ3hjQ0hVSzdUemtpeC9xdGhxOUlXV2Rh
        WG9Gdlh3azN1c2ljY1VucDYwWm9zckFYWnZLS2ZJejhLd1h4VGRxM0RQcXdaZzVW
        TmNXdUcvYkJzc1pLL0x2a3g2UWsxMnlTOWY4L215YmZrTWxpVU0yeHplNElxN212
        MnRFKzdRMmxwaVBPTTZjMVovVC9tSElqeTFIcEV2a293cTVic1hOUUNLVnNhZlFX
        K2hsdHNidS8xRllHS25wRmJnQkNRaStka1JCbTB5dzVvbUdXS0c3WXJtNVlwcHgv
        OXRiTXNhNzBiS2EzdjZtSHpwZWVSOU9Hamxuck1FbGd5SzVuLy9PWEhoU0ZkdlI1
        bDkvTVRMaWxLQUJHTDlBTnV3RFlaNU4ycTN2THVqK3NtVTZLNlF0SGpSd0p2VHBK
        ME4yS0ZjRWRRSE1kMGRrYmZMdkpoUUVIck1GYTFEOS8vejZ2dCtOUjRPc1hGMFFm
        Q3JROEIxOFZqSUdBTXFMUDY4VGJSTE1oblJQWEZ0clpoL3RScWFLYzJ2K0djUHZS
        aUxrM0tscjNidCtabEtkd25FMk5aNHNWRzNrTkR2d0s0RlpBZStoRUpzSTVYbU51
        VUJHdXcvMWZHMDl3ZmZ1eTZPT2hCQnI1dkVyOGo0OEtLSlh3N0h0S0g5ZnFtaWt3
        a2ZockdSZy9rMmZVb2NvZWhERjNpMXFOQVZML21XbDU4Uk9DZzJydHZmNklEeTJi
        cVVlUlJpN3JvNWJ1aTdFSDFvU0RlS0l4NW00alZ5MjljYlRuYlRXOVlMVG5WdWN4
        ZXlLSzgxOWs1QXB3cUlSdi9ibWVtVnFNRUlodG9vN3BzbWpvNEJnMUdYYTNoRUxw
        SE04UWFjQXlnMkV5YnhkajY5OEwwZDcvNEEyR0JTQlFna0hweWN1S1M4Smt5NmlZ
        SzVRUEUrU2gyUCt3dHUxVXNHclBpVFBHRHYyRWt6cUp2RGhvWFZCR3hkOStQNTZL
        WENwRGdzaFpxN0xGeERMNGVqM2RXQkswcTBRQks3REdPaFRJQmpoaHN4U3RORmtU
        N0N5ZEpwQ2ZYUE9lUzRZNlRKU2N0dnJFY2kvNTNVMWpYSjVzNWcwQlVidDhBN21n
        Q0x2U2NuaUorNEtVeWhzUlR2aHAwM1hhekJQNUdubFQ5eFFtRERKRVhKdStsaHd5
        Njh4dmZIdEVSdEtHZjBQZ1JMbFdzVUNtdFVHVnhUQi9zMTZ6SENRSTR0ZjdKVWE0
        V3A0TTNocFA0RVF4UVdyLzlSMEtUdHNUOW9FbjVHUjU0dUdQZnhiTCsrMS9SVnFj
        bGZLYWdxQk9TWFlzOUM2K1h1RERsR09peVFML3BLOUpVRVpQWjh5dWVSRmlBdwpY
        UTYzVXQ3bzhCY28wbkJhbnlqclJJbGxJUzNjZ2NkNXBmaVYyK3Jhei93Ci0tLSB2
        eFN0eVBnQ0dOZHBzUU5UTklGeVk3eWNVKzlVbjVrUUUxTXJGQ042UUVVCmeSZbeP
        xfPjU/7aKuTeCBVHLuRmSc9sqy0KabY+3c7I+a5mX+YJxwpXMc1nkegSDZKkJZQG
        L50jeKNzuCTXCHM=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:48Z"
  mac: ENC[AES256_GCM,data:+Hg7pZH5JxB1vKl+1xp3AP2fa7HqkUaIn8Uy1BZuTbPOQcTS10P4u3zfnIoNQXUfYQItHL+3bTjJeyvtvHU5Tvk4ESeG1+r8pGDR0pW1M+gCwzyQuPRggzaccViKlD3VRhxGJmG7MB8IcOeVhSStR853AoM6hIKPJU3YA9+4qiE=,iv:Vx4ghqFAagHtbUUwJxqPmmmgssVUPv6qBK3KnR24Jck=,tag:XLdvFNEYSt6Kby2jc5ZzSg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
