apiVersion: v1
kind: Secret
metadata:
  name: ovh-webhook-config
stringData:
  values.yaml: ENC[AES256_GCM,data:8qlTLbWbWCx/DjNtwDNyWECQRNfk++jgJD78Ms7SC/avs52gO4DzrOvPSZzbBeMelb5QuycYi/n9KKDR56CzmcYkdnUCPlSn8DULNPZyfWwvfWlwrF8NKcb39dn3vtqy+/Th/hk8bntbzkginC9D9qu8ox6PKnWCFaJq5zC+pI4M4pyo+OkiAOn/dhpQOYEgJoPXif8gDrwfURwHaqqbjrlFoyefwh8rQk41g1iN1f9gIPSAzIqNDQTowScullL3GcnfXF8zE+oeDucLeSUEQZ5izlRE2+WOALAYV0yeof3GtO3razo/jidnc1FsOFAsUFKJZTzSKyWrt1O5XV5/ECfDeM1nCuThQQhG49bxgZqMQtIFTBbFRrcsb06leIdRO3+89aJCmj6bYTZBRD9cLVRMHPB3d8lixihJo/rDYoXAI6eKU7dqAawI70v4JLSU8uxAbTNQw7z+yuIbAWgpiNid3WxkblmKSFE4IpfLIq7EInNYUVxy0yh7UmVzuz+lDiLqXKzA0wEbGJPdDPM16FMw12P123m3vRTfVfPfk/zRNcED4tldQkPPTEHx9aQqPITDDFoRRVkZkKFBMEAbutI/W2/Kcp02m5My/C+P/qw2dyKA50BfNxcKSGOHyat88kh3zWTdyCLbhnRgrV8JRJHOKPtshaGpupkvYtcnKysXRlbkymU=,iv:Nii71yFkat+mAFdRAYQ9RLHWqYQQlUp5xBhl/JoqiFo=,tag:CMggFsKOTkfh6otOFVyBIw==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDc3elA0VGE0
        MDRYc01xNlNJQ25SN21XVUppeW9OYkVWc2VidURFWTZ3NS9OQnRFR2lCZWo0RzhB
        eFkyUm9UMHQ0NWdrU0NRais2ZDJFMlZGSlAyWE9WRUVNNnk2NXR1SDNtOFRlRVV3
        V1NtVDJhLyt0cVdCa1RYUG4wZFl6cGlrT3RLRlNFZEF5VHYyRjcvTGl2bmJ3dTAx
        WjN6UnNpMWpaNXEvNnZUbWZDMFAzUmhNcUxXSUxpY3BOS3gzZE5xZDZHb2FIOFZF
        ZXlvRXdMMXI1Y095elZKYTUxSmhWR2QxN3g2c0ZZR1ZRVk1YVlBDL2tiZUZaaWdU
        ZGV6eU1xZlBWMU5YRU9UU3ZIaHI1elBkdEJEbzBrNzdLeVR2Z2Q2dHZtRWtudHNF
        VnI2Y2lCWVgxVTRzMENONVR2bjJwZVN3S2pZVUFFczVaQXhOSXJSbmlDaWUvMnV4
        OUVtRXVXeXlxVGFlZklMK0dzR1JWK01VNStRVlFheTZ4cmt6a1JkblJ5TEhPZXBH
        bHFMcS9aTVNFeE9uQ0hZMUtiOWlwZGNvRWNhbDhJM2dXb2o0QTV6TzVaSm9Pem00
        alpVWm5lRndBZjJuVENDL2hINGlXdzFMWnJGOTNyOTdxNHBlc01IekdEZ09XQ2Rn
        ZEF5T3dOSkJ3dHNPd0t2eThqdjFKdzJ0Q3E2eHVNOVdSaWlmcEdEN2lzVlorWlYz
        eGp4d29wL3dGcm9rc2ZGWS83aWFPeW9wK0hnc0czWEFXVVlnZUpRWkh2SU1YRXI4
        bTJOblljeFVxZlNoWll6dXpUalM4NHhsaDh1a0pOY21tY0FmNFhCdGI0S3ZRaUt5
        eUlab2dQYm5aSjlvOHQ0ZmxsckZyQXdDckpoM1lSdkZqN2FXQlpZSjBSeDhTQmpQ
        aktrMUdRSlVzaE9ZR0tKMGg4NHMybVg2dUhoNEczWEpYeXdHVlpmNEJTa0dwanEx
        bkc4R3BGNlUwczBjQnNuQkhHOHo3bURZcU04UWlGTTI4bEdiMmFlT0VVWFdhWkNG
        RjV6dnd4VTE1d1NzUXZ1bzVra05wRFZsekxGeWx2b1d5YUhDb1ErUVZIK3ZuNjM2
        amYrbXBGTVpWaFh0MGJhdzB0eFZVU2YzbVJuMWhibUxycmZsUlpjVzJRMGdVdUhS
        SmFSRDlIN29YeklwQjdScStvRjR1VDc4TlZqNk1JbktUUDF4ak4rN1J5bng1amhZ
        aERJN3d1RDhiRTM4L1JwRS9vcjk3WlEzR3hOVTc5RG9CNjU3akE4QW90Z012cjNz
        QWVhQ1JXelN4YzVCaGpZY1NoZmVaNFhpVy92bG9WSUoraFhRTC9RdlhxV3htdUtP
        YlhTaHd4eE1HSTFLQ2NUNTZVT3lVcjNuUm5QKzZlUFU4TGYvZDE5ZFdneldWbnla
        cEw3WEtnK2FRL3BMWlFrTS9JbG9HU0N1NlRLZWx4Tm5qalYyQ0pzb1FQYzN1dytG
        UW54cE1qMVB6ZlRYRWsva0ZDOE1jSVFZV0UvUTdKWkhlOFJJTGZwQThBRy9QSk11
        U2ovRkk2aFFBcWxmbXhaaGtqUU1FbjRwN2JYRk4rdWEwZi83WVRGdEZjNWM4c2pi
        NDlxMjRCUG9Jci9veXJOVXRweEFFcldVZlBvd2kvL1ZZSExKcDZTQWxpV29QRFZG
        eTczRGFUMUNoQUNjaDR5eVhHR0pUVHhOdkFZRE00T1E1TEt4RHlEa1VqVkp6TVNq
        R3dxdjBiRFRaOTk3eVFDOGkzUEJ0ejNLdUN4RjFpK1NIVzRhZVBBT0NXUUR1ZEI2
        dmx6aklvR016bFpiTW5wRHBTdlN0VlYrS0UzV3NtT1k0eE9hVllJZ1BXd3dUOEpR
        Uk13emJiR2RGVEtIZGtnY1E4Tno5QkN4Tzd5dUpvVGRQUGNwRkVyVkY5cFdyQTRZ
        VEtWcVBEK1dxUWNMamVGd2c5U2VYR1dTWnhOYVA3OWRpQ216WGVKK3QzTi9GdwpP
        ZlJZQU96M2pOSGoyLzNDNmxKWHlUUWZwakNnNWJzTXdLVDBhSjFZZHRJCi0tLSA0
        bkFXQjNGSDFuRFhwaVRrM2xvM05IWWliMzJlb0dteDNxZ2pia1RtWUNVCvp33v5y
        +YJW2lN4FSZrwusDyh9mjVSQ9RtzXURdpgKNsElFiq3UBxJaRKC3sbMTzAjPkK3j
        MfyTiMVkX47yVP0=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:48Z"
  mac: ENC[AES256_GCM,data:W4npyt0cWxdU7r5DL79fUJ/wEjJDWmz7xZOahsDp16FezBfea/wU36RCoMIv/Tyr5XgBdnkD+sMJIoROolftiWwUaTSEaVniAumqgjO7oITqFN+LWj6tq8+7hp8NqBHONTc7A1QjmyO/omEScz40Cff3SOoIva8RUGNBQeMH170=,iv:OAzwueQIQRmROnMmseHhGg4uD4F2sJGTLiUa5LFp4+0=,tag:C8vIeYN+YQQDF1+B/FEXSg==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
