apiVersion: v1
stringData:
  address: ENC[AES256_GCM,data:1ely+Wdjx+fUsI4CBA4JWQg/VJ/Tl6B1zPFK00vAa7gH1I6nLEPbp5EIYZwM17gBGXx8ML5nnq09YugT7Z7Wn5lDslcVrcU6KXzAnLYXh4tY+SAc1lgEazCZt6YA9Sr21bKRLYOjXXPqh2cx2GPFpqxUG/w5L/3+EA==,iv:3Hso/M7iFw2fQTKgl/04prwSCbgdFURsEn3TX/nky4w=,tag:XUfhrNQIWjQDZ7u8sFA60A==,type:str]
kind: Secret
metadata:
  name: discord-webhook
  namespace: flux-system
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFFEM0g5MGdH
        UW9VTVJHZmpqNm45M2lhcUJSaWpNc1dQZ2xwK2dQNkVIR0ljckVQK1l5OFZhdm8y
        VjhnSzhKTG9JN1g0TnFsS2hrcVFmYmI1RlUxc2xBenMvbXBBNU8zS0VNcHRiY1Y1
        YmRnRGMzZjdxeHE2N2tpK3BnYVVJQnY2UnliTlpraXZDdGp2Nnd5V3Qrc2h3V21o
        YTFlTWxUbi9vdlNWc3A1NE51SU5jY0haWldjb0UrUHBDT0ZOVWdheGVHTy95d1BH
        ajk4MVlVWXlwb3FnNTJNZFFNNDB0QTVmUTcwaFNoOFI0dVFKaXNwVGNBbks1anM4
        R3MrVGl0NHVrS1FuWktOem42TjhWV0kzd3lkdktQL1Y2cy8ybjlRN2o5d3B5cVFJ
        RXBNTjNDSFRDNzJ5aEpNSmVOZk1jSHZpajZiWVNDaGdmUUFsa2ViT0dvZWMzd1BC
        MTV6eTArdytLRm9tc2kxcXhwdkxNV3FRcFozV3hscFdaSG9UY0RHejN6ZlUyOUc4
        MVVKWVpFUlN4ZWlGRnFRY3YwUkV2Q012bUpEZm5RNk1PNEpNZVVVVjBIemxoNGcw
        OWxtaitCeXd5ZHlYcEYvWnYvQUprWEtheCtZTkpTUWFaS2s3TlFybktKMFAzY1pO
        QmIwdmNENlpRZWYyQUkrNGhSZnA3aklSOENpWkF6ZkNMUkt2SXA1UmJkSUZNNldn
        WVlGTHAxdTVRNnhnczZTalhmZ083YXRaWHFCay9zYWFKcVZTWWEwRFo5d051VGJq
        UUwxSWFYWnBGQWg3RkZETDNaNHhHUmlLRXhvY2hiZ1pnRjhvazRCNXNycDNmQThO
        N0pxendGaUxaRnozQWRFRDgwRXBtS3kwek9YY2pBSnNTQ0dCdVJsT3RIL0hLd0d2
        aVJJTEhKc0NIUHdPRGhncEh1MHBrc01uT0lUTG1pVkNzaW43N05vbFdTY0dieS9T
        OUJVZzRMSTlCTTRNZjZEcjE0Q0JZUmMvUTl3cFRXSGtPVkxEei93a1Y2dzZOcWlB
        ZG5FK3NsUTNRbkN3bzkxdXdqbTRpRmx6eWgvS05FelVHOXFyemNrV2Z2b3h4Z0ZH
        akNZQ2lqMHNtWWt6T3hISVFMdzZ1a3NoRStuRXY1cjFKbjVlcS9URC9NZWtvRTRi
        YUtZOEhYbE5ZY1cvYWVVM3hodGp0ZTJTMUV6MWlJWEh2cUZhUEFMcEgxU3ZNUENj
        eWo1MFJDNkJwbGIzNjFQM0MxbW5seE5jQ2FCdXpRUGREMUJiWkJzbmptVlhxYWYx
        eWRTaTBvQ2NTR2lNU0pxcjdEY2ltVmNTWU13UUFwNkZaODA5TmQ2TEU3RmEydjR3
        aElnVmE3UFNuZk9FdEdUaG1RNEFzeHZVTGN3RlA0cVBRS1pNaXUwZnBRVXVnb3VJ
        VG4xQ0NMbkJrWXhzMndTVjZ5UWRlcU1wM1VhZW1taksxWm5XdjRhdGMzUTRFVkxk
        Z3VWb1MyUnFqejA3RmY3cy9BV2czU1A1ZDI0TCs0SnhJWWs2bVJPZTRzZmc4cmdh
        K2htQVltd0pkdUpmdTlqb0lTLy94RGtpVlY0S0FBdmlmQXVONjhwV2lzc09vQVd4
        VHdGclRac0hxZEt5OXFBaDF1bDF6aTBOZ0loZEI3ZEl2UUd1RE9DS09QVFp5aVJq
        cHhSdGFyUzR2V0xjd3lCMk5RclpXWW9Fb0FBY21VVjBXOHBBNWlqbWlYNUhvVU1i
        U01wSW13MkhMZnc1WUNrUURWQ3d1MktsU0NPb1dSSVZJNnNVaThicVUzUCtzZVNF
        RDZqZnppUGVDMFkxeEdpZUhERDIwOVdVS0N5RGtETEJ1bFF5YnBocDVDa3dVNGYv
        Tm9paWtTTzd6TngyYW1TNE42ekV0Yi9nQ0dPL1dMamt1SkhqQWpKcjkrQlRmdDZI
        ZEM4cWljU2NILzVaUGswT2RsRXppbjdYOC9ZYWUwZlVqMGdBcmlPWXZXWUtLUQp1
        VlFPWDJTUHBlSTMxS25HTHRkSW5hdTVCZDkxL3IxM2hOMU5YK21JazNRCi0tLSBV
        TWp1RFVTRmhUeGxxZFZLWTZaN3Zua3lzMFVNVzBXVms4NXR5UG5CblVvCtCN7xXC
        BLesWftk4o1fYgYcVcdIai0ow0pRRBWY0TgIVeLWMXFsbCA3+CMAh6H6bI0LcHYZ
        5mHDlBFwZGKMjxE=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:hztXdZGsTLNa8D4VN2fHaPUH5+dtqrIkXi7X2Rht73dcZSsypIXy0V0HrFTrOPly1eAkvPk/cjt6NqSqGSA0dh1tf5VHy/LKE3kHqsIm+A7nuikabst4z4BsQC0noMCP7ZsK9AMZb+fKwuYvbyl6iFO5krcCLuOEx5KTPCZ1vAk=,iv:DvGCIuHgeIk+fWhRRh6K0MpTtCWEItksevcWb6/gfVk=,tag:Jw+uvcPxY7DLx6LMGi5TzQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.10.2
