apiVersion: v1
kind: Secret
metadata:
  name: explo-config
stringData:
  .env: ENC[AES256_GCM,data:4DpiQw0UppJ+IjKBxVV1CoN5XvMDZZnfpOveg0jGfNt7FK+m1WumTeU5acu/vQyPFJMbuGn7OYNze2nMeboKtZVx/rBKW+Md5C5Saob1XrHYKOgT1e3pcFgvToeNCdNpdeufFUkuEngppe9vsxP8eMHhDEeZURJLdqqc+pwdRQB/OMenvLul//syGf2ClGUv+DNUEKMKESwEtGy5yxw7eJRewdcIG/uUNI+XzwJ0DHuB6BXf8NJOPY51ybdhST34RktUFM/YYmqCqWyDyyTcF4yNcCK9c05HOkKbRUFJet08/iUODtpbMaPkptKEEZ61DUjGRBmq72X+5Ulalz5PnzbvwlzfiiS/hV8KZ/LvRJng11QOj0LFD35jXJHqdyEZyW5hG6W4wvy7jh6RIBEdeNuJkVTULfWzq5sSIrXjguMoyzM+8IYiVEw5v/kqSl6inKNUtoSJgPnYZPMWwRIJGbo85bWqSyxWpT2zZvjiFeBVV8DPFNq6+rdmz67/mO+sg0o2V1ctBOdw2vkxM9v7rqklzRXa2UwpHbmuNban+brLX7KKD30lL5tHsIcaY1zUl/1+b6lg9O+1fBoxgvmnVeh10iMp8pX6WOWMGA7fWohpCOF05lVrF5at5+fQOb90umssqmwXgm4+6E4cUpU6LGTQ9BTyjcFFUtUvKg7kARzOiUKEwabwo7q8gu7yVgbpwo9u9OYttxfNLUO21LaJaDf3fpM8GsIklFiDVdeBIbqScHK6l0I13l+4+/5otNskqMu9PG2bOSA14igM1BS3fXz+lQx/gZV3h5/PMmI4vh4BNVWLHyvs5vwPlKd9oifzKS1XjX5fM2D0pxXEhJ2RReC2qi0rVsHF7T7hOeV34lXt6zmUUX3pUPXEZhDZ8QJ3a6WjJA==,iv:PytrO7fl27o93DoY6yPQazxG5qIzFG5j/1YmC1W6yck=,tag:bTxhVPrj8D9buv1xqAbMGQ==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IG5SNExjUlcz
        OEZDL2N0bjl1OTFTZTl0RDJWS093aXNNUDNGT09yYitxVll2VjNueGs5S2dLZkVs
        K3RjWHVaZ2QwR0czSzc1bFlxN0w4dDlBVGdPNXZNNnFsdFNZWGZKNGtPMmcwV2VN
        bkUzekd1dmFSc2tLQWZMRG5PdjVxTnlDZGtQcUt2Zm05SGFDWUFxVkNJVlRzelpi
        YWZaOWl0ZUJnSytObDQ5dlUrVWtyUmNpV0lPKzV6TmF2TkpkVlUyQnpvL3JrSWpL
        MHZQUW1PbW1LQkRQVXgvcit3OXY1bEY5OXRVcUNMMWZJa1lEMTRycXFWM2xyd3B2
        Y3kxSGRyRmNlQkhKS2VXK1c2SlRKY1planROMEtLRmRJWEw4SGphVmNsZ1I1aXR5
        NWkxWDRYd0dLK2U2TGZVQVpOWnR6ci82eUlWVWZZTG9DZXRRVXgyM002K21JYzN1
        Sko1MExqNXVjTkxlYnpSYUJ2enBZUTJWUmMwNERRelppYTNpOHFOak54d29abXU4
        UlpYc3VHMzkyZlRIWmhEbWJMdEs0Tk5kYXIxMm96UkFvU1YzVDgyeUZVbmk0aFNO
        ZUlrWlM3OEp5bFVKcHdka2xDc3FlK3NRYk1QL3dBOThaenYzWUxFYjY4aFRWUEdB
        ZWdwWWEzdG1XeFZQZ0hJYXZHQ3U2SHF3dW1GL3NUelJNd0ZYU2twTUV4N3BjblFp
        N1I0eG5ERVNaMFdBL2FpdXNxR2FYaDN5ajBJUE1pSUQ2dytZQ0pvZzlJaTQxWTRy
        N2lmSXI0UTdkTU8rRk13TDRtQTZpdFA0dWIvSE5Nd0ZHZjZUMEN4cHZ1aHVMMG9x
        Zm9OaUNBNDlqRngwdGNBK3JIVnlJTnhCOTFwS2dpSTBRR2RvditHN29WNVFCdWcr
        N0RVUm5WOVNQdm9Xa3RMOE5FWlF4UFBFYnR4aS9DcC9MRWVRaVFnOVJ1QzJiNFpX
        THI4YTRVVmRHZFhsc0ZVSEJuUVJtMjU4VWxmRUZiUjhscUVrZ093ZzcwRXo2N3p4
        ck9Vcnk3YnM0Zk1sRWFlWDJhbUc2RHBnNEVQb0xkTUVVcDVCeWJocEhkQ21HN2pY
        RThSbmx5RjlQL1hTL2xEV3pZTDZ4cVZ5OXNMcHNXWDJFc3pHZGxxelBzVkR2V3FG
        M1N2S3VzUm9VMmpRZEgwREs5TlZ1TEl0NzBBMDlmTHUyczMxUjlXNkhCV3hOd0dk
        K0hnZ3RuZVZhSVlXcUM5MUc3QVVjUm9NbVU2OStDNGdVUG1yaEMwMVh0aXdkVHox
        MEFYYkdlbWpHRHk0d1orUFBkcTN3VGtZTGtGSHRwZDlSVnNodEpEMlRXZUhQSHpu
        R0h5d05sQWtwdmhFTUlyY0krT01KVDgyVEtqazFpdFpvTmlMeDFWKy9vSjFBclJx
        bCszWDVXNzN3S1hWNHNobGJQcS9qdTF6aXlya0hEQ0NRWHRTcGJRNUJtOUYzWjZL
        Yk5BTDJQVEhMWVdPNzhXRzJQVjB3elZmTXpvYmFoVFYvSWNWRGlIVG52V25qNW5o
        UDBDb3BDcWJRT2lBam9UNUpvaHowb2UyR2phUlExYnFIdDZEVGc1Zm1POGIrQ0Fn
        MlowaS9ZWElXeHBndkJwc0VGNHZiUmFWZ2JOeW00Sm1LMXJSZTFUVkdZNEdyclBa
        dFVsY2VkZjhmVjM4VUhSRjBDNFArNmZJY1huZ0lFbmdrbW5WdzlWSU8rNlFieExr
        NkVTZlRhRGozMVNuUlZ3UWlFTGVGK3QyMXIxYlZKRW1qVUlNT0ZiM2gxMEZSOHRF
        UG5OQitOVzJldllPVVVtam1XbWg3d3R5NXNtOHlUdTBoNkZ3c0dWMGZtZVdSSmRy
        Vlp2ZjlnNkQ3WGlmeWhPSU1RUzlsSUVLa25uMDdieGF3OGtESHhmWllGSmVrRFN4
        NjNCM2tERHIxblUvTkt5a3lDOXhLTEppTXZ1elhZTHJWTjBhZHNkWlMwOTVkQQp1
        cEhLcFh3cUtKMnFjRkJ1Snk0SlJQTk4raFdpdkwyMGtPYXVMQXFYOC9VCi0tLSBV
        cUo2K1pRaWRSeEYzUzJaWCs4Ym82aGdsVzZiWEU4ZGFTYUswRjBzQ2ZRCvWiYPqC
        xVvR7MuaUPmfP0Y40mpFPpeBCNmpEyO9V96SuY44oaKIoXyCikS3aOSK3LOova8k
        xqzuCNWqXwqE66g=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:LMW8C4kdlk9588R71RvRFVwu2rgvGxzJT+hsi4RmJ3SuhE+FXmk3sgzGeojIInOsPvC03NbdFtbYz5s1663uDeHh9+zj26FwYKQBnHcMAGRiO2vFMZBesdFldg8dLfTEOWVOD4GxgGJFojdShAjGs30p8+pS3zR2pVGWxpUEElU=,iv:uayIFHWWIdMWvdiO1FQ7QPOITRAJ1L7kqvXAgjR1jYI=,tag:XCuSTVthyYB0tUSpwcXglw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
