apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metube
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: metube
        image: ghcr.io/alexta69/metube:2026.03.08@sha256:3de82b0a8c1339a501e0b6ac00e8fa65676144c9ef78f7cc0b6003348d01a97f
        env:
        - name: DOWNLOAD_DIR
          value: /downloads/shows
        - name: AUDIO_DOWNLOAD_DIR
          value: "/downloads/music" 

        service: 8081
        ingress:
          domain: tube.cocointhe.cloud
        volumeMounts:
          - name: jellyfin-shows
            mountPath: /downloads/shows
          - name: jellyfin-music
            mountPath: /downloads/music
        volumes:
          - name: jellyfin-shows
            persistentVolumeClaim:
              claimName: jellyfin-shows
          - name: jellyfin-music
            persistentVolumeClaim:
              claimName: jellyfin-music