apiVersion: v1
kind: Secret
metadata:
  name: falcosidekick-config
stringData:
  values.yaml: ENC[AES256_GCM,data:FOe3MIxrC25DVCAUufWZAOD9GZVz6ONtrUfuFiG311W3eyEekleFrP2IYkhQ/6A+si+PGWDtccr5qlu/vmQjycyH/gXxNOp36NYD80/Tx1TxMqz+3f8MRVNeEUYIOPJMQZ3ffHLtmGdmZ76eAxFsKgnpdz6/5h0bTENxYtO98spfLxnE4cYpYOYIcQC6kjPRTXyLEinrgheEeNXGJFwi5sleRpJi0Do0afJg6eOduN6o9mjNxT1eqzXvxFTxzx27WCMx+AN/kBGCz2xnx8pBQkhTI1wRdDIWvwtheQAUrDHKPslR2ZREQobbHI4SbEvk2kMfnfPmoCEOTNsMXF3M3fQKj9g6IALNLfnJ7WDAhPy0B+12Ee28MeqQhRSjTHsyS7jYbm+eckI3/rD4tlcOhK9fTTz1OdE7KqE+ek0tUC0w94mcbzZlxjvrQNQ=,iv:cUxi52eIP0w+X65wIq73e2N+ldDc8ntqVKQfL5HqQ5k=,tag:vo7/ER3J9LQdn2O3WkFcLw==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFB1QTNhbW1D
        aHRJOXBVdHE5TVBTRkx3YWJGVWNkMnpBT0RQQmR3TkJvOTB0d2I3TXVVMTJSa0lz
        aGgzdHVsRWVDNWdrU1dkRDhaWXN2UGZtYnNYVEZaVXpNSUxpNHJ0SUtRakhmQnEr
        bHBqUUJRTkNmV3FSMTVhbUxsK2NjejRMc3lmUlBIK1BmaiswajcyS3NpcEcrQXZV
        OTdXMTQwUEdmM0NZaXZDMy82d29uaGlOdkd3ZHhvRzVUckZIMTdPVm5SVWR2b0x4
        ZVlQekgwL2lkNGhMNkUyeGwwTXFrYUtIZ0ViSmt4SW5Pdmd6TnlkcUdyQXpLMDIz
        NkVtNGpOUUxHR0ZTOFpOY0VpcVhrZnR1TlltYTZqNlVtb2JRdDRCM3QrZ1hQNjVY
        NVY3QkxiYVdCRXVpc3Z2UEd2MTJsVlBDc0p5bWR5cnozNERNUk52bFVyK2pNYjVH
        bG5IRjUwcFZ5Rm9VVnArQlg3OGxHVk9aczJ3YklKZmtUOWZFQWZNZkoyTG9wbzAy
        eTg5dUtPczlqSUtQTEludFQ1V3U4aW9BYmdNR2JkMXhPeEIyNnMyQUczR2xOem1F
        V0pSOG04RDdSUjNYSTNQRDlBdDQwSkNlaEhYT1craGJnR1k3aGFWaG8zMkZvWGx0
        QWgvSWxoYXhwZmxvL25hdFNlWFNWNmN2NnpDT2d2ZlNnUlhaVnN1a3pWcTdDUzNS
        VlZaN0xCeDNzdUo3cHFZQ0dQTmorMU5sdEtKakpOWHBCVlhaelBrRy9zNE5JRmVF
        eTA5ellYWVBhSXZ4bUVweU5BdkRJTkd5bkhFTDBzUnUwc1RLdTJqMmlCbnlES3Nh
        Vm5ialdtVkRBdTd4VmlJa01xWVJGQVc2bSs0czhyaVRpd0JFd1NVN1BBc2s0bTVM
        b2FnSlpjaUJCdmp5bS9MQmE4K2FIdXRIMkJYaHBJektFV0JDMktUNzNqWnZPWGhY
        UTBCVFY5WVNqQVl1MGZIdUJjZ2YxNnBRR0hEY3Z2NHIyd1d5NkNweEJOUksxMXpL
        TDlieCtlaC9aMWYyN1BWUGdERnIvY2l0Q1d6MjZTbWZ1QkF0WVNpanNzRHFJZUE1
        U2dLVExJbmpGQmxhVUJtU0pMSVNnTXJTZjJwN0o0eHpPTC9wd0VJNjJEc2d3eWp3
        QXFEUEtZN2MvKzliTE1EczgwUklUdHpqNm53bE0ycDh5S1hYYUR2QnlCWFJ4WVEv
        cG44SWVOU1o5d2xKbEE4Y3NuZkh2SzgvWGxpTHRER2hHSm5adGZ6M2RiTUR6VktL
        MFMxaVY0dGpyNXNBc0d3SFByRFJaYWhWLzM2SlBrbTdFd0F3UzJ0d2ZqeG42UkZF
        dnEyazlaZ1N6cHhza3NDQURVNnEyalhYZ1owWGNqMWhMVWNVYWgrSHhBYWVEWjdI
        clBmSEQvZ0NYaVVjQ3BCb0ludkFEaUp3YnNBTHp2VnA3amVhaG5UOGFqaWhLeVJC
        REtjQXl1Q3hwOTQ0QXFXeUJ4Nis3SXVUWmI3Z1pITm0zc1dDR3ZjYk90WWRRUjNB
        VVNHc2hEZnltaUFOQXRsVG56ZGNTM2pnOHQ4RU9LZE9CVHBpU2Z5OHo2dzVuaHQr
        M3BsSWNLZ2t0dUFpN0ltbWVtdzdHMUNaNmU0bmp6MjhvTVRndEZHUVN2SDhWdC9j
        TUJyU1JtS1lxZWQ0Mi84cWpRSHRSUHJHaW1KZGlOSXJ1aE1jTmQyVnZNZHNRdllN
        aGdZTnVMYVA2S3hKb2RQeWlRYUpMZ2YrSmx2dENMeFFXK20rTjdCOC80bVdnNmww
        UjdINUk2RnFzTVRiTkp6bnRLUWNvSFp2bERSRStWeExNbnVNeWdJMjR6cGN2NTY4
        S05TTno1SnNpRlN6c3JLaUtOS3VSZUFUbFJKWEVSNWZ5REUxY0x3VUtVMFRvS0E4
        UTNTZ2IvaEpwUUIxdkhQZm9sRk9rTElLOGFOQ2ZpbjZhbFZONWJzMWs4NWRZZwpl
        S09UOEgyTXlrKzdqUURSa25pNTZMUktZVUJsWFZLUC9MS1NsL1dLMk1jCi0tLSAz
        bTZoSEtEMUNFZ0F2N3hkMFJHQWVodE9BanBYM1JGeHFWemcxbFR0ektZCrz693YD
        S/q3wAvYVniG4YfNbXX0wrmkAVtUGQH8KAWbm2BbXDTBBzpZXUuK/Ocynt9WikWl
        3T4U5zG+OccQY/4=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:48Z"
  mac: ENC[AES256_GCM,data:OlUywM6Vb89qQpW8OIwzcin9uNU6J9HQrCdg4796KnA9KpCNoGKkgOcuXmx+ew0LG7SD/Q31+u0yFPHSe1Skr0Os2n4CcIxkQpCd4saFBzjHarReorbXCP/7I4f1SUfmcmgQQvzg+CAGrGHcXNR84b3pz/JunVgnjTR2GkrsABo=,iv:DQwOzQbrwetB7QopTAUPidLEEobmoydBKHg2qcmkyb8=,tag:RTj3m36goF25N8n/7zNtHw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
