apiVersion: v1
stringData:
  RESTIC_PASSWORD: ENC[AES256_GCM,data:3Fa+bt6/rg2DwAk=,iv:kQPTo/Y55JU0sanzKf9ICk+oM9eskjYIAkgLYIvZBCw=,tag:c7N0phEmV9gcfXZRwEtPVw==,type:str]
  RESTIC_REMOTE_REPO: ENC[AES256_GCM,data:RrbyluRfuMYWfdc2QrVpTo1GsFLX4hizNTahgH8jz9n6Eb/58LKabM5kPci7Pu+zgHgUZLw70dbLskwhc9s7fdM3,iv:7eT+05oFKKk3IX1Z0OHt2nKRLIM9ZJZ6fVtPtBB/lLI=,tag:4LIAG4EZHg0SVolIkoULiA==,type:str]
  RESTIC_NFS_PATH: ENC[AES256_GCM,data:K+J4I/rXqMVBqAOB,iv:/9oJu0oqj3+y/jB7qDkuUHiWJlBSvBBlnWZ/eYt1CEk=,tag:KJSphxJnA9FPB/gZt4e8WA==,type:str]
  DISCORD_WEBHOOK: ENC[AES256_GCM,data:EP8qGfo/rslinC9f/mIyaQsKorK2OArJfKdGA6lxfDuUKBr4vtAvovWAwdVqRhmH4LfYsJxE7bFZxzat61mpH6fcMYYfEQ55A7DOnqJ/gF89VW4Hg72ahwWKw7VfA7bRmHBFxA1qO9ZjZCqa+x/GnBKF4h7VUaSqaA==,iv:gcjorIuBh2p5NXtVthfTiue3+kmF6x0EUzsuoANhzpQ=,tag:ZPI024UEiNgftw2PsY8Oxw==,type:str]
kind: Secret
metadata:
  name: restic-config
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGxocnZmb3pa
        ZjlMTzJSU0ZHOURlc29qTHUrVG1ZU2FCeWVtYjNMZGI0dVR6SHdLaUE5Y3VZNWRP
        SWIxL3RxRGhTbmRTSjRLK0xzV0lLNjNmNThYZWp3MkNCU0piSFV6ZWhRN0l5aW94
        cC9tem9ZeGRjRFJtaWtPSmRGSVJYWllGdDhWdld4UFQxVzV3UzN0ZWJudWM0aERX
        L0VXRzVlTkFpL3M2cnJoRzhHWGtOZERoYm1XZGM4cklBMks2Z1ZlL0hseFpwRllu
        c3lJUHJPRVFxSEh4MDRXMllaV0VwNGd3d01PdGs2clYrMUhsc1JwR0NFTS9DWS9o
        eFdTdnd3UUZOZTJxLzJSMkJWVmtCTTVqTGxISllGa3FJb0lkTEMySnFaT01tVmtZ
        L3RHRHRtNlN6TzFSOWwyQ0V0eHFhSE5mK0hKUlVGc1ZETU9FbXY0S2pwWlprOTho
        NmF1RWM5YlVOL21PUEhPNnZObE1GMkp5djN6dk4zYWU3WXJFVm13Zm9HNTlJUjJF
        K3ExSHJiYXVvM09CR0g1RTQrWDgybndQWXZXWHBFZTNUYTlFMmhXSmJYajVVNk45
        ZzVVSnUyeVNobCsyNGgvUHFMQVBlMXYyUWVVZFdUK1p2Ty9tUnFnSWV3bTVPTGhs
        ZU9hZEU3ZTRVWlVqbENxZ1M2ZHZIUTJKMHJaSDh1blNTU1pvVzdlOFd3T2F1aDly
        MXhkbGkvV2dTSi9JekFQdkIwdDZzVUppQjlBS1NrNEFuaDdBL1VaWks4TFd5Qlc5
        SmdRNzk1OHJHVE8vanVCc0YvRnd6OTBUTmsyeG9JalpwVlhRRDY3S2srRStoRmhL
        ekdOS05vL3d6QkZLVS8zV3RMYjNFUXcwbEYvYkZOTmlpeW9lbzVMay9HL2dIcXd6
        ekJlVGFjUTJOazVWRUUxOWhYT3VlVytvSEhoaERZekxIcXd2cmg4Sk9od3RuWDFW
        TTRJVG1nYityUUlHSEJtRnZ4dm9paHhmaVRtaU5BcjFqZTV3Z2dKNERiZGN5R210
        aDdBb1VueGs4Qmw1ZnN3a0NyVmZFM1VnMTVkUDJzOGViVjhNNTVjQkgwWHpYQy8x
        RVduWVlqTnBVUllUWVBLSlVkbGNhMkZ3UFhSak9aRnhLNVlxSGh6dUV4WTZRb08x
        VmR2YmNRZ0xYTWtqZEoydGxXM2F6eVE3ZlVFQ2JGeEdnUVZTVkpZS3AwK1h1S25w
        YUUybVM2NnhsMXFLZVl0ZnNSbENPS2dhUDNRelY1bDNnZnlxRVkyQlowMTFEaFBo
        VzNxc1orQkpmakhTS1hxRm13ai91amt1TzJCNDBkdW5kamdoUXNETXJLNmw4a3kx
        MlFPZnNxc2VReUZMNXhDUUNUMUhQQjhQOXNFU3k4RmhDUmZsYWVldS9sMktiNjBH
        NklZblJFT1NhdFc2ZkdGcVhqWHhtRWlqa2piT3ZsTnNqU3hvelhFMVVSb3JDVGti
        aFBQNDB0SlQzeWV3OTB6djFtd0ttSzNlSE91VmhpaTl6dUFadE4rVGhOZ3VJUUc4
        eldMMEtRZkxmSDA4c0hWTlhOWEhBdkVBTll1c0lWT0hYbnVtOWd0R3VpeWJtdnlE
        SFJhb3RlTWJ3ZG94YzAzTEVuVFpTVUFlUE93Q3d2NGRtV3NYRmx2N25EWHp1cHJ5
        Ym0yMGp3SjZ6MDBuLzlwcXhvTFdzNkpUWWpCOGtYMmJBcDlKTWkxUjk0cUlkNmU0
        THEyV0srTFNBRnc3WUFGV0I3bHNPOXlYWk13QnEwT0czaStoRUxuaUtsNk9KS1FI
        Q2U1ek5KeW9LWTZ0Y2V1clZzK3RkcllqZmlnbW56RFA2K0FwcHgrVy90MjMveEhl
        OGRpblFjWGRRWDgyTGpOOFA1TEJZeGZpWFhaS09mSS90TVZTeVNvOXR2ZEVzS3Uy
        Rm1JdDBNWEhuRHJrT3pXQjFaaE9QWHRUV3pkS3kzQUwzNHBYY3R5bEhwOXBJZwpW
        RE9CRlZFVERyN1FnRmQrUlpnRnViampQSkZISzRoQTJKTDFjeUJiSkhjCi0tLSBD
        eVY3aE1UbzRvcG9qMDNDdkhabWwrZDRtd1ErS0pFMDdLZFI4TXNoUy9BCmES7JcQ
        88pWxiMicdQ6ZhnGNX3z51KZk4a6mhsX01Qqqoflg7kGFN4gSym0eWpyl+2uT2Oy
        WnvqmZqLHkT45dA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:48Z"
  mac: ENC[AES256_GCM,data:C/ZIOEVVdvnTxjCo4rRfbRpZYcJ9MAUNB/1SXHfzlGcaWLcqatzGYt9ztS8GlLoKRqWi16gJZxsD3RKzzCTDbC9neVhbQootipX/scPLwRiRPAvc3NXJHdCsgAIAKLbfNZJT6G9c+lO4PJMIsZwbRSt0egEbZZj6TF3FspnS2bg=,iv:bfacVcpkfVDQ8x3aJxQgHMxeLCGRFS1/pyT5htZFltM=,tag:RVm0IIFF3qKXw5PYAm8Nng==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.10.2
---
apiVersion: v1
data:
  sshkey: ENC[AES256_GCM,data:9lUTiwROAfrMTj1DceveiIKarSbITVLJvBPJUBTJXUaEFaPjuNgPSRuRcEgAErX/ut5UHgssr12xh8Uo1Aql/l5LbT52B8eNE6V0ikvcm/TC8Wd/ga4GU4F7XVFhMaIfUJoVIAfcUirkZylgmxc56M9hG4HSnjYybwzbCg1YQLXC5NPHrFCIPAXG9Md+LjhwblZ7Z5OQtMgIqFJ+pREwPKYgTtstUw3TzOmekGYaZD1FAiSDB3YDoTEuhgSPvLvgNDaal0kOS1d8ENmRHN8QyG5LVpNKkF4WazSlmV0m3qVSaNC8MKAuowyX37M5citpk/p7EewRuGR0AJcLYXQvyy2Dx4YZur10q6Qmxn70MA9CYWH8f09GMJAYpZJ8LAZbKac/A5fVWqJvVhVjVpCULzU1LVGa7lCztQqNBcAh3BefwA6ffN0p94QEhkLCN6rfWlm2IVhfxca/M4ttqzTT1DH9qtHXtrVSTXmSuN5d/TrxCUhf+E0XcMoZPtnjqcQ14B5pMvudiJ/cGCRnv415yFb5mXyBWlDRw9PKHQ8yDaGH1gShkDGplXZjwW1jrve2jNmYtBLP9bagWRM28QdkzAtd0k3ImDsz7E5mK9qa/iOfpphAF2K5NgeR6qfAYgQoM8Rw0ejvTElyjwIeYbTQiahNQjbKe+QthWKDax2tHlFgKkHJeKNLTkAi2iyZ+C5y8OrdHXeYdAVUC/I3jpLm6wmWlj8=,iv:1Kfok31O/FA2rNBE0oNlvYqRQQgtC4gtYqwkPnE6KbE=,tag:wprFoqihmkUpXGegvmNJXA==,type:str]
kind: Secret
metadata:
  name: sshkey
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGxocnZmb3pa
        ZjlMTzJSU0ZHOURlc29qTHUrVG1ZU2FCeWVtYjNMZGI0dVR6SHdLaUE5Y3VZNWRP
        SWIxL3RxRGhTbmRTSjRLK0xzV0lLNjNmNThYZWp3MkNCU0piSFV6ZWhRN0l5aW94
        cC9tem9ZeGRjRFJtaWtPSmRGSVJYWllGdDhWdld4UFQxVzV3UzN0ZWJudWM0aERX
        L0VXRzVlTkFpL3M2cnJoRzhHWGtOZERoYm1XZGM4cklBMks2Z1ZlL0hseFpwRllu
        c3lJUHJPRVFxSEh4MDRXMllaV0VwNGd3d01PdGs2clYrMUhsc1JwR0NFTS9DWS9o
        eFdTdnd3UUZOZTJxLzJSMkJWVmtCTTVqTGxISllGa3FJb0lkTEMySnFaT01tVmtZ
        L3RHRHRtNlN6TzFSOWwyQ0V0eHFhSE5mK0hKUlVGc1ZETU9FbXY0S2pwWlprOTho
        NmF1RWM5YlVOL21PUEhPNnZObE1GMkp5djN6dk4zYWU3WXJFVm13Zm9HNTlJUjJF
        K3ExSHJiYXVvM09CR0g1RTQrWDgybndQWXZXWHBFZTNUYTlFMmhXSmJYajVVNk45
        ZzVVSnUyeVNobCsyNGgvUHFMQVBlMXYyUWVVZFdUK1p2Ty9tUnFnSWV3bTVPTGhs
        ZU9hZEU3ZTRVWlVqbENxZ1M2ZHZIUTJKMHJaSDh1blNTU1pvVzdlOFd3T2F1aDly
        MXhkbGkvV2dTSi9JekFQdkIwdDZzVUppQjlBS1NrNEFuaDdBL1VaWks4TFd5Qlc5
        SmdRNzk1OHJHVE8vanVCc0YvRnd6OTBUTmsyeG9JalpwVlhRRDY3S2srRStoRmhL
        ekdOS05vL3d6QkZLVS8zV3RMYjNFUXcwbEYvYkZOTmlpeW9lbzVMay9HL2dIcXd6
        ekJlVGFjUTJOazVWRUUxOWhYT3VlVytvSEhoaERZekxIcXd2cmg4Sk9od3RuWDFW
        TTRJVG1nYityUUlHSEJtRnZ4dm9paHhmaVRtaU5BcjFqZTV3Z2dKNERiZGN5R210
        aDdBb1VueGs4Qmw1ZnN3a0NyVmZFM1VnMTVkUDJzOGViVjhNNTVjQkgwWHpYQy8x
        RVduWVlqTnBVUllUWVBLSlVkbGNhMkZ3UFhSak9aRnhLNVlxSGh6dUV4WTZRb08x
        VmR2YmNRZ0xYTWtqZEoydGxXM2F6eVE3ZlVFQ2JGeEdnUVZTVkpZS3AwK1h1S25w
        YUUybVM2NnhsMXFLZVl0ZnNSbENPS2dhUDNRelY1bDNnZnlxRVkyQlowMTFEaFBo
        VzNxc1orQkpmakhTS1hxRm13ai91amt1TzJCNDBkdW5kamdoUXNETXJLNmw4a3kx
        MlFPZnNxc2VReUZMNXhDUUNUMUhQQjhQOXNFU3k4RmhDUmZsYWVldS9sMktiNjBH
        NklZblJFT1NhdFc2ZkdGcVhqWHhtRWlqa2piT3ZsTnNqU3hvelhFMVVSb3JDVGti
        aFBQNDB0SlQzeWV3OTB6djFtd0ttSzNlSE91VmhpaTl6dUFadE4rVGhOZ3VJUUc4
        eldMMEtRZkxmSDA4c0hWTlhOWEhBdkVBTll1c0lWT0hYbnVtOWd0R3VpeWJtdnlE
        SFJhb3RlTWJ3ZG94YzAzTEVuVFpTVUFlUE93Q3d2NGRtV3NYRmx2N25EWHp1cHJ5
        Ym0yMGp3SjZ6MDBuLzlwcXhvTFdzNkpUWWpCOGtYMmJBcDlKTWkxUjk0cUlkNmU0
        THEyV0srTFNBRnc3WUFGV0I3bHNPOXlYWk13QnEwT0czaStoRUxuaUtsNk9KS1FI
        Q2U1ek5KeW9LWTZ0Y2V1clZzK3RkcllqZmlnbW56RFA2K0FwcHgrVy90MjMveEhl
        OGRpblFjWGRRWDgyTGpOOFA1TEJZeGZpWFhaS09mSS90TVZTeVNvOXR2ZEVzS3Uy
        Rm1JdDBNWEhuRHJrT3pXQjFaaE9QWHRUV3pkS3kzQUwzNHBYY3R5bEhwOXBJZwpW
        RE9CRlZFVERyN1FnRmQrUlpnRnViampQSkZISzRoQTJKTDFjeUJiSkhjCi0tLSBD
        eVY3aE1UbzRvcG9qMDNDdkhabWwrZDRtd1ErS0pFMDdLZFI4TXNoUy9BCmES7JcQ
        88pWxiMicdQ6ZhnGNX3z51KZk4a6mhsX01Qqqoflg7kGFN4gSym0eWpyl+2uT2Oy
        WnvqmZqLHkT45dA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:48Z"
  mac: ENC[AES256_GCM,data:C/ZIOEVVdvnTxjCo4rRfbRpZYcJ9MAUNB/1SXHfzlGcaWLcqatzGYt9ztS8GlLoKRqWi16gJZxsD3RKzzCTDbC9neVhbQootipX/scPLwRiRPAvc3NXJHdCsgAIAKLbfNZJT6G9c+lO4PJMIsZwbRSt0egEbZZj6TF3FspnS2bg=,iv:bfacVcpkfVDQ8x3aJxQgHMxeLCGRFS1/pyT5htZFltM=,tag:RVm0IIFF3qKXw5PYAm8Nng==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.10.2
