apiVersion: v1
kind: Secret
metadata:
  name: grist-config
stringData:
  GRIST_OIDC_SP_HOST: ENC[AES256_GCM,data:T9esCRc+TUuZUk2AErr7KFPC10GSYn6I9/bnNJU=,iv:xU6FLlG3IEp0tLajfn6aimzw1PoF/JHvb0F2T5u6DbM=,tag:1bqbL5pnFMXcel6AycKbCw==,type:str]
  GRIST_OIDC_IDP_ISSUER: ENC[AES256_GCM,data:m4z8j1jEv4O8dshWhLGslwyNfWf3lP2rcU2mkv2ctC2W23cZREum9p2Gymr4ix4JtDXHtm5dm2n8DpkFQ11ZZJg=,iv:qdBnz9U2VlIcsLAJQHGtYtBXQOdESgV+yZB1vCiSXPY=,tag:AVnlrPlRPmAZYUsE8c0y7A==,type:str]
  GRIST_OIDC_IDP_SCOPES: ENC[AES256_GCM,data:ldGSo5My/RUdX4jWHgupAiraSSU=,iv:dmU2uTjcgwrLEVgBAujVqPcWlLGc6ERpqPa2NAfNgRo=,tag:GqESwYs56TAa+iHGKhE8Kw==,type:str]
  GRIST_OIDC_IDP_CLIENT_ID: ENC[AES256_GCM,data:UM1sL2T7FAIr+ACeixWRMRTDKZQdeNv+xjyv7KFkPTA7G5gv,iv:nbUTEiABj5gOwqbRpj59kwBk1BsQ+XcOaLys/MhoTys=,tag:1oMAadpCrGTD/gUf0/xDyA==,type:str]
  GRIST_OIDC_IDP_CLIENT_SECRET: ENC[AES256_GCM,data:D40SuAmuCN1WJt79YcMR4s758suXCl6+SV4i/Xz5Pto=,iv:fHupEXGXszIlIF3mZGE7FiyQ+M8N0LMMoxLfzz+1jFg=,tag:C/GbY7rwb6HhhvD95vkRrA==,type:str]
  GRIST_SESSION_SECRET: ENC[AES256_GCM,data:d8A3/V59XjL9TubKVLvA/FopgRBbt7tht70lkYsg2g8FI3okQHs2nwNx9PZsSQf16VUm6F4GsQPIJyLQAZI0iQ==,iv:gtegh4YLRRYNAe7aF1LltZfNwNRGowT02cn8Kbsw6YU=,tag:ZUwtrlAPGoAn05LwnLaNmw==,type:str]
  GRIST_FORCE_LOGIN: ENC[AES256_GCM,data:crxZvw==,iv:4xmhqFMYp5YZ4R9XVcVdG502VY4Gkvvz4bdgm8t6eFM=,tag:iQp2kptA4B3+JD1mgkbl2Q==,type:str]
  GRIST_OIDC_SP_IGNORE_EMAIL_VERIFIED: ENC[AES256_GCM,data:/AW/5g==,iv:GOJPWEiDEfp3lfssOa4i2ZBSPPvILKJl9NTFo7q/yJ0=,tag:OzkUa3s1z5+mw8qW4ayXiA==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEUyZkZjK0hp
        RWpoNmY4dXpGRkpGclZSM2ZrVzhyZjJtWFhXS2pzM2FXamhSTmFteFhPSHc5VDVU
        d2s2UzM1dFZ5VWlRcndRM1BoeDZkMExCd0trQmVKWVFQTnczZDlqZUp0aVBUYU5M
        S210V0ZCRVlua1lXYW0xMUkwZ0ttL3BjVkZTcy9oZE1TRFBrQzJ1NzhhTVBuK1pR
        UURQeWNYL0Y0SmxmNnFlZ0FqV3krYlk5bzNuSDU1Y3lKVHlweHprUmpPclRtS2xR
        RHU3amtwM25QYlliMkF4MmlsUFB3SjFOSTVSS05TaFRINnFFTGhXQ2huK1NXYkxF
        bFhadElETVBZYk01ZWVLSW1kUm9VbU1NWno3N0p6WklvYU5SRmxoUzZ5cmFMMWll
        d0xUUEdORVpwM2pMWnFLMDI1Yms2M3Mzcis0aVI1cVhmcW1Hc3RoVDIzTC9NVXJD
        S1FheTlqRy9Zd01IV0FKRDlzSythbmJoVzNNd2hNalZLOWpoeGVpb2t3ZXA3WGJ6
        M2t1eGdtTjZRY1pneEorZXo3alhLRGxSS0dVMHo0UlhaZ2NwSCthMGloR3AyOUpJ
        RnR3a0VmTktVYTE0b2xzaERyTElwTE5IbU1CS2cvWmc3b1RqMlpTMk4ydWg4NFc5
        VU1SelJYSHJlUVg0eHNXamc3Yzd2OE1KN0J2SXVpZ0REZ2J3cHIrSW1vY09kRmlx
        RDE0Q2JreFZDbTd0SzA5eVliUmxhV3FvbllKTDM3Y241RVZ1QWkwWkROVXZ4SjJo
        VUtON29vRTUzQWZrM2t6Y0NUZ2Q5QUpXQWxGTmNEVFNUVmFOUzZacDR3YWFNMHlj
        UGdmQXdObmVLT2pJVVYxaTNrNnJha0IxTXJXcHJtdnBWVy9kUGtvbW53ZnBENG8v
        NHV4Z2R2Z0RhNitGbm1zNXI0Q3lkeTVEcHhuTi84Y0NoK0ozWmx1YWNnMHdMTllZ
        L05xVkZicjBNdjRabE55S0lwU0ROZzRwVGRuQTJzQUdBbzRMVGRIR3FnVjUwN1hC
        N1IxcCtKK2cyN0lpWThlZlVQcTBMNnFkQnBOemxCcnJGekEvN2pXd1JCaWtaa0M1
        OG9KOWhJUWsxbUpzd01yb1pIYWF5UWdoQjlQOGtmUTQxQWorK000azY1WktPejNW
        dzBoNEY5SUppdTQwWlhwanB0WHl0dE9LU29scU03TlI1L0FIbUlHYlBNZUFleXR5
        WGFzK05aNDNML0F3T2RITkNQWW14WEpyY2c4MDRhb01BRkNCcElIdENiQ1BEZWw5
        a0pTazJPMzBGQ2RWdlQxYWJ1R084cVMrZElCMVlkV3g3RDNQVC9UbnlvR2FjK2NQ
        Sk9CenhUMzlqcHkxQkNkNktKYmRveTlpMDVjWGllOFJhU0xKMlBSRHlWVjd0eHl6
        RE5aM0Z4NnJVNnhNMmxzRWVWVVVmaWVFZjVhUlNpR09iME5EZlJEUm5SeHFWQmw0
        dTFncmpwTXpyR1Q0clJQOVkwdUFWRHBoL1ZidzRjMmdUOEFZNHFmVE9BUzQ1V1Ev
        dFV6cWlwcVV1YVRHN2VMMFJDc0lSNlp5VWIzWGg3MXNma0FKUHJBdnZJL3JoUUFj
        Q0ExK0JEN1RSenM3RnJYVVdLbjkyRTVkUlBSL09SUi9XZWJxak9aRzdDcjZBSHV4
        cmYyYUpPaUF1T0JVUG5pQ3hSSlF0VERwOHdPdjB1V1VzUGdtd3NIei9DTWZSeVRl
        K2dhb3BvUDdQcHY0dFBweUlORlJtOHpxeEdWVC93cnMwSHQxcU0rRUU5Tm1wWUJy
        OEw5WUFETDhuS042N2d5RmFzaU9mZkVjaG8vVE1WS3FMN3RBTXFkRGZCQ2kvbVgy
        cHJ5OURlY0ZtcDhEQUsxSGQyVHkvSjhxYkJMZVNja0o2NC94YVhicjNOQTBiSkY1
        cG00SjVnN3liR1JQSXFGZUUyUmFQRDdQSENtVFAreEVnaFNqQUVoczZtRkVYZwpl
        OWFaNFQrM2N1bU0rZXprVjc5UUFEY2p1d3N6bDUvd1lLRERJZ0psNlNjCi0tLSBN
        YmVyc2hkTWlkUjdBZnFReS9Ib2JNTHE5NFpLcHk0S2UyMlJDT2IyMXhzCqPXzK1a
        1RRVS648iP4Uubabi7kpSRdtqQ587X53pbtfKrXzAGPV12ABlW6VUgt6yH47Ho5R
        GYPgjKm4iKJDdgQ=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:1YqhbnV2HYOARlfk9gIuydOkbu8gUuJ+PLJHWG4jdHFnSOBAz3fhbmkgtSllx12h5PknK4K4fD3TwycX9w17W3V0NYjtwR4vM9mCaScx6AV2PNbSRAaTs/HpWXz5iyUBELUFDNAoNCMnGLymIxDPPg6jXSc8Y5Zftkz5+abvgb8=,iv:aZ1XkCT9Atu3P4qrByWTrrOrcNQVDsA9OnHvBdnaAvU=,tag:Kx67rxyORzTiOGVnPmBV8A==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
