apiVersion: v1
kind: Secret
metadata:
  name: groceries-config
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:IijtcdFEfJ9ckbiF2TIw8PqCGmTsxFrBDPkZB1GBaYfzZVQL,iv:aomczyZQcmiIaJTmiFZTfYEK070o+8Cyi3FX+WfGehg=,tag:793Imml+KWFYpyjGgl1zGw==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:AHfyj3C/vO4Qs0EJO0yEGUhyXBp9VckcF4aH5aXFSc0=,iv:lpa9DeRghQV3lmqRj7dRsy8mvGyg30pTyhw0IPGaeJ8=,tag:q9gHqCKpgFf5IMBJKEAV9w==,type:str]
  OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:XDnbE1Yc8Hgjw2GNkUQb6XoPL5jhZ5wgahQxE/EwVtjM5VS7wupjnl2nyxq8cmMNaqfGsH4oQpHAbmqoWH59YY8=,iv:XUCb4DD3LsP6qnrMoF3xbVRAuN1gnI0q+K32A1arrM4=,tag:P4QR2KmlO/iu9GL3PIPFYw==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:zGncHp8IgbgJzh89EjbgfAXxfFiwuLZ/R8vmIOli0COxabvki1DyPKQAQQ/zY/YEKCeylL4pEOtNRJ1ny5ldmQ==,iv:TuE5QDRf7Ng7P6pqMTuaxBRTFvRPCTAqO/MCKgSDAQw=,tag:eST63pfeYGdWLbwGBntu6w==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFlLdWp3ZjVP
        eEh3czNnK2JhVGQ1aHJ6RXZQc0RtdTVTWTd0NjhvSjhzVGNEdVhXTGM0UWREVEg4
        dGJLTjBSQkNKSktxeDlORFZWMVVST1U2OXVQYlY2TTVLNENrOEl2L3RWWEp6NjF6
        anc0c0huaWpDaEIrUFpSQTNwTWExWSszNTY4c3M2cytiRk9YUG13VGhmUGdNVVlK
        MDdCWjVHNnVyUjZ5TFhad2MyNHJQNkhnYnlFemdZRE0zMkM0VFNIR3dtSkRzVmhO
        SnNSSldjTkxZWWxZNEJJcWRWdk94aXpVamV3SjRlNXVLSXN1Ri9zSkdPK2VhUy9D
        bWM5UGRoNUhEcmFSQXdINjNBRkZmZnNrWjZSLzlPTkw5VzNWVnArY01acFVqTVFr
        NitQYnl2Zlk0TFN4NWJVcldNdHhzck40c0dXYXpxaEV2SDkrcDM3Tml0NFFDU2ox
        NnROeGc5TGJUZG5BQWxkNCtDM3JtMWFvMHMzdkRRajRFRUhqUVczSGRZcTRQeDgy
        Z3AxQnVPa09saU5zY3I5aXRKUzVlV0hZQUdBTzB5TlVnMGUyek96eEhVTVZUaTdJ
        QmVsUVBuZExVZ01HWjNJb25FZldVZGtLUW1YcHQwalZ0R1RRZlI1cFZBZTJ3S25i
        ZzFHSE05T3JjekEwNFlXSHhSVGpDU21EWFBId3B5WTZEWGR1dkZENWVBdjV0NHcz
        K0ZhbzlWeGMxdTlCVlpIS3RTbmVQM1lPTjhLb0hIUEZ3eVYrbDJjZGhTUFd6Y2dW
        b2xqdWp0b3ZIQ1pxU0phWURjSDUzUmtRZUEwbUJwbUlVYlZoU1BYbld6SlZnQjJa
        OUh3L3dLbThBTzdNclN4NXIxbXJhNkExNFNsczhINkQzaU9pb0NhckJhZi8vYWM3
        eTcwS1JlUnc2bCtERWJpSkRpZ1ZzRWRLTU1wdk5Wd0oyWDF6L0I1V0lZc2hGWHJ4
        bjBkcWVkQUtoYVBNZ2tRR3JBclZ2TnFXNFFHazNKeDZmZzhNaW81NXA5UlcyTGdW
        NDkxV1hHRFdnRVlWUjFQVmdOZWJkYkxoS3pxSUtTUUxrdjgyVlM1dGxOQUhhNE45
        UDlZcFAyYWRLTE1hSnJOWWFmK0ZmbXkwMnp2b3ZrSmptcFErRFgzY0ZxL01rQzF6
        RTVORVg4K2JvKzN1RUY0dHhrRVgvdXdTMlc0MjBhWE5zS2x1RzZKbitXalltRkF3
        ZFBDelMxSlF5VDZDUU80RlBxU0tnR2NpRkxETmpQTUJKeVNXZ1dBV3NDdFRIV1h6
        NEFYOHc4SW44bUZXM2FOSVhFWTJ5VEkrbW5hOHUzZEhzaEFaNlNtQlJudnhIK1Y1
        eGRlTGFjOXNMMHRTRW90M05tTExmVDFYWkgyNTc1YXMvNzVpY1RZZG1HeVd5N1kw
        WkV2YWlRRHBCenNlQW9HemcveWhxaldRbzF0NkpiWlU1MWIvb1JvZ1F0YWd3aE1j
        NUVnTGRTaW5XWFBxZUNRUjZGalJxNGE3eGlyc3VnZGd5Y1NtWVRmU3JNNW5zVzMr
        VGRzYnMwMjlmN1ZMMHRpV1dmSllHSlM3QWh5R3RrZVA5RXJKQ20xSk1kK1c4UHBo
        RTM1aG1PMXg5L0F3cHpwVXlwQVMzeldReE5zS3NmVzY2SENFSm9YMHlXenM4NldF
        a2c2SFVqYkpET1VnMXlRVFR3WjgwNXNWUllMenhxb2dYeDA5TDJuVGxaV2Fidnk2
        Z1lDbkpacXlJckkrWmFCd1g0ZGh3OUdkWVFEOE5GbEo5T3VSOTVSb1MybjNKNTlm
        L20vSVZQc1VPTE5hSXFJdWtqYy9oY3kyV0VYT1B5cTJ1aGg0UTJHL1V3d3VDSEZU
        UzRIdFY4SE4xa1BSZmdyQkppOHdXM3Z3d1VUOFZjT3Brd3NtQ21mSmxhSk9oRnRp
        VHJWQ0llMm13RDdZWlFxYUFyMFU5UlE1aXJDRXArcmN3NVg0OXgrcmcyTWRDdwp6
        NU16OEhIbGRwRDQ2a2I3U2UxTkhhbi9TNFdHaDF1VzhkWUpGaUZyS29nCi0tLSB0
        blVLQTdicmNlaHgrb1E3SVdncVB6bWJHRytCR3FXcHNGVVF5OVEyOXo0Cr0dqkN0
        wa4jS5CBtKkiZu9egRH3CJDpv9jaIznVmq8MaizBWV3fR0Au+Ol/Geh9Y7bTED8u
        9XBbIS+FbLyfuJM=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:8dFysOlK3O4ucLTauJP5DHVTFnks+ZUVLNwzVLGC9PksXA73gjvpoIiiok5s/ryw+bo0a6GyjlNKJ7JzmPB/sOXhAd9OYJd5U7OAnQUhiSlo7DJEimJ28n7i/mbF9Olucvbe/ockWT5vRWBVzMF++5nluKB4rkgpOocP9QjVe4I=,iv:FG89HRfKr/JPrW/rbzlHNxbiPmu92QRRIDugzkJdQtU=,tag:j2GdWk8pysZLwKIk+2qqlA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.11.0
