apiVersion: v1
kind: Secret
metadata:
  name: haven-config
stringData:
  FORCE_HTTP: ENC[AES256_GCM,data:X1SN+Q==,iv:8I29J5rH9HvrhY0dLqclPAht0MFa3VnbepRmyLrQwxw=,tag:O0Cv1I+mXyDDw4ZfdOSU/Q==,type:str]
  SERVER_NAME: ENC[AES256_GCM,data:Ym7gB2dlfyi6XxY=,iv:8oT9nSgYzjxi02x4T2zlin/oHXoy6QlsodwffcSImnI=,tag:COkxNdvOdmjYFYfMHtUnVw==,type:str]
  TURN_URL: ENC[AES256_GCM,data:FEzJLQ48Vel1ZghuxyPRNArWF9dKGMc7azYlqPQL,iv:cF9AgN78nDeZmdfx7+u8fhv679NACOPx2sVvV0HPPSg=,tag:wCpdpxd4aewOrGfU/jOVAw==,type:str]
  TURN_SECRET: ENC[AES256_GCM,data:29PIXZUVJF2jWfZYXLc0UPORGqMlhhYOOV3dx1+wLw4LDu4O1slo2Mi4wK937g6dxzYanAgHdkQJtZwsnoJWmA==,iv:v8IU4e5X5eYnh4R/3czBjo2ZRWg0kC0Ve9DQNgku2QY=,tag:wL6fddDxoUZT8Z3YdblBxg==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ODg3QXF3TW05M2I4SEdV
        NWU4dHp3YkNDYUVXZzUyWG9Eb1pVejNka2dRClkzaFJRMWZ5R09ySDVPMitLTUhm
        MFUxblBLSnRoSzNMY0dBSUEwbHg2OEUKLS0tIDdNN0M1dkJpd0ovV2tnZ3JSUFZE
        Vm5aY0t1K0dKeEN1dHplZFJqYTB3ZTgKnIjNHhfGU+R8REGJKC2+pCWO7Ibdi1r3
        YHZks6rT500Y3kEDmn85IObKW09NaLW7I49/2FjbrpwQIxNgxtaoMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-15T18:52:41Z"
  mac: ENC[AES256_GCM,data:KloDC/OX7mPoweXY/b9e/paJaY/D+H5kK6cyKeP4Om7sFzvWmPObEDyISElsb8ErS+Cj+g7P+pzbCNa6KSqFdE+Ki68Y1geum5hwbWHG6ulHoeB9rGbKqWNejA9Ayx9Id6UrIkI7YuBz5AD8mpYtvNdkEJ02LiCzZBr+VTk0UI8=,iv:vpXo7mzM3QhuKoqDsJhjJ72hB2pt+7aP7NymRyO44hU=,tag:8CPSDBggawLPn/BdR00UMw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.1
