apiVersion: v1
kind: Secret
metadata:
  name: haven-config
stringData:
  FORCE_HTTP: ENC[AES256_GCM,data:6sKGSg==,iv:8I29J5rH9HvrhY0dLqclPAht0MFa3VnbepRmyLrQwxw=,tag:2MBfq3CxTYwnb1hXrH4IWg==,type:str]
  SERVER_NAME: ENC[AES256_GCM,data:mSUYnSBu3CjwBjI=,iv:8oT9nSgYzjxi02x4T2zlin/oHXoy6QlsodwffcSImnI=,tag:qiTytmKQHJvRzT68G5eRrQ==,type:str]
  TURN_URL: ENC[AES256_GCM,data:xftEkB1czEJNgz0/ZaxZzt8DYIx8UhF4RNP/Hs5M,iv:cF9AgN78nDeZmdfx7+u8fhv679NACOPx2sVvV0HPPSg=,tag:poR5dnp0JpKTE95TPN+0zA==,type:str]
  TURN_SECRET: ENC[AES256_GCM,data:vWsN/HvvsXGHNvOfoxM0NVnicpQQlogKMzNkk1qwFuBDW+6QKyPNcI50TyGfagNtv641EOmCQqyOphFgh6PcTg==,iv:v8IU4e5X5eYnh4R/3czBjo2ZRWg0kC0Ve9DQNgku2QY=,tag:TayOa5LjARi01LxfnXDNlg==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEVCREduSFZx
        Z05PRlJ5aitJQURHV3hKSXBOZTdna2lqdTdOYjViZC9jbW9lMU1xSk1zbnF2UXJR
        ZzVXV2ErZkYybDh6Y0FLWXg1OWlEbWx5L3BFcE5zMkJtandvbU9kdXUwY3k1eFRy
        TmhOc3JtVTNnYmNYekNGWFd5d2VFZWFrYXUvSjhkNkJqNm1vbWhucDFkbkZ6QXRl
        djJUUVNkUUdIeHhjaWVIYUJ0UEhGVE1aVjl5ano5UStSMEJlOW1SQnZITjNGT2pF
        aFBtbExhTDBtZk9qMnRnSEFLQnJMcFV5TjRDOWIvaXVCVmcrdTFaQlhjU2JPNExu
        cW1wVi9XK0V2SmtUK0FoQmlFT3JSdThiSDYrUjZweUVmbnZxRUZ4YzJEYk1LK1cy
        cllmT3JSR3hLb1d2SVpxR0RvRmdtYWNvQkRvZ3RkNDdVcVY0VmZ2Y2hGcGVDMzBU
        ejZ0aEplTkxmcDZXTVZiWG9xbGV1MDVqc3llbTRYanZXNUVzV3NLa20zQVgxMFZT
        STYvajliMEVweHptT0hlM1g1bVg1VURSMW02aVRaZGtsUVBDSTYrQUN5dDE0QXBi
        cGVtc3FFNHVGMEx3RjJDK0p3Q1N0WUxVc2VwMS9UdE9Mend6QnlqVDlFaUdtdmZD
        UnZaYWF6NU9DeW1BUUZPb1o0MnU0R3AvSlZGU0hDNElBU25wZTFCTFk1YkZMakxT
        dDBKamhycnJCNHlBTVBXRzRJcFBQRGgxckc0NmYxUU5ncGZ3UzRBL1paVUZuVmUx
        TGNQUCtsTTRNOGp1VGErTWcvMWo5M0Nla0p6Zi8yN2tBbkVLZG42Qk5YY3dFUmJo
        akxxNGt3am1KOGtDQmJ5K3lYbnJVdWdXZUNuNHVaNjJDV3BDeENGeE5oNytkY2JM
        aENBaC9Vb3NOYkt2NWppT01Jd3NiZ0hLWW5pTXBOeXI2OE5mMngrUmJubFdhTTdX
        NVlnaGVuZEhpb2ZaZTlka3hkbkRCUW4wMXdLWVVmMFdRRlc5T3BENjUrM3VXSjg4
        YU1ZVUIzT250Z0lITUtiN3FoM2djUnFKOUpQcW16N2kxd1pJcEw0NHJZTkFrM0Fn
        dnM5SzlBYTRXdjQ2WGMrK05MaVEvUDZuTFdKOFpCeURJNGR3aWtzbjdMSkJrYThJ
        UDllNnljWjVCNnNmK1JYUDQwQUFrZ3grWWk2S2ZoUkttK2dxcCtJSWwxNWl4ZHpZ
        enNSUWFJakxnbWcyMUdzTS9JaktSbVQweVdnUGtEVHlKRnJyMHhvZWpRaW11TzBa
        UkJFd1NTNUZWY2tSM1NoSGFTQWVKMm01NS9mZ0tKeGgrUWZzQnpGUThMbDQremFJ
        M2dwNnhkelNuc1dtdTNkeU8rSTdnMXRlOHVHWTJHeGhJeTZ4TGF5QlhGQWpMQ3Ux
        THk5WGFIUjdrUk9qa3BFYnhmRWNQTlhuUUdhc2pxbmdmVXhlb0syWEJjS2Zxci8r
        YklEWGxiWmw5VHM3U0Q1aXVjd2Y3UHBSa2RFMmtjMDJ5Q211TU5SUmlEOFhlMmk2
        NTlzd2FONU9iUnNzcWV4MDYrWXpHVUIzL0ZESk9GWmdYWktqTDdyc3RHbnE1ZE95
        TUhTNXczS3NCc1ZaY1J1MkNjWXoyRTEvS2tacjhsTVhFdmlvVDB3U3ZXZTE5aXk2
        bXdHRzJITFFWZnYvWFYxaVVEUTFTZ01JSjh2YnZrcmVTM1FMeExlcjMwQTBKR0Jl
        Y2FXZUFqcm9JbCtlVWVUYzJYbUY2TUFHMUlSa2diZHY3Tlc0Q1lKWDUvMFJVRlZF
        VEdhWkZSYjhrazNUUDZVR1pQUlFac1JzalpTdXNWVlJydzViT2RsYjl0MnQxdHRl
        bHJyc1ZJQlBhR0FMNGlUeW9zbjJoT29ERWNhVFJFU1RENE9ndU9xclp0d2kxSG1j
        eGZLR0d1YTg0NjRST1pOUW80WllSa3kxREsxZ0l5Nk1FaVVUUDFRbURBRlFKQQpz
        WUNaS1NkOHhjeXFLL0pvWmU3c1BDQVc2QmVUVWlHbWZvRFc4TjFDVEVFCi0tLSBI
        WDV0REJoTFIvVWtBeW5oMnd0MVYvMTNVd3RZZjhmSTB3Yzd3UGhxVHdZCkEVT7Tv
        +VGiSi8IkSy5Tbz+ye3gtsy1b9z/iKV0uBYS7dB3B2Wao5R4GJjLLx+Kvlkn94wU
        9cYwWWxtrwnYrMM=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:0zjqM3R9uILxSea41Q/iy7AImaiJ7/kfdY2JRILaI4bNTilKbruIGr6TPuqqdrWJnbV2y7bqokszxBQLusY7gZGenPPNMAgj7SdU4CsvhKIoc4INX1jvJh54HP9L+gbe/GfEVs0cfGHjQ4rcFP1AekHH1ML7MZClhHo9KqTeQzw=,iv:9Tx1r6N3DX+31TYK9rQxpwwsGW59y/7bYj0oAHomQpk=,tag:8bsIp2QrHQ9V6MtVB7dvog==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.1
