apiVersion: v1
kind: Secret
metadata:
  name: nota-config
stringData:
  OIDC_CLIENT_ID: ENC[AES256_GCM,data:PLlaBbHs8jakW/xeMCjuFXu17kfzK8MGfPwvj+Bn+WU5h0gu,iv:WZG5USYV1mLQA+TRTU1trnwsKcU0HwBxm00xfQJ5KJM=,tag:eYOeyBFh+KZcEUnsVjv1nA==,type:str]
  OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+oSH498yuaHi88/JRiaCtvzQsOYNsSSNLwx8KFi3ZAk=,iv:+tN7f2v3yDOIQ/qQ1am2KhN8OFlA9ujPCBQLY9JuR2w=,tag:ZYa6CZkGDSUmNY373wdbdw==,type:str]
  OIDC_DISCOVERY_URL: ENC[AES256_GCM,data:nJcUdBEG93DUJJyRywvihrrlLRXhWvKbtYDKGo5yXi253fmHQjLsLAriPR9sOKK5zrPkJ9CAu5BaSC6Zb/S7Khk=,iv:5dekG1AmZ3mAS4BP/uUQ6EPWZs9/aCL5hxJ8j7pwjqQ=,tag:rr5stmHiHtmndtGQBHvLKg==,type:str]
  SESSION_SECRET: ENC[AES256_GCM,data:ez+dM6EHM8F/NA5U9oltHHtkNgzHiOXmuRFmz9pTsuMYy//grNsY944Va5jjI53VVYg0H3m50opkF1VNjiNK7Q==,iv:DpuFi34d3pQW1Tz0ogXKXaNNW9jxyzMfc6OLM9k7AT0=,tag:2EhZ/x8bGWhHb9iUkzy8lw==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDQxNndENGNt
        RjJtaHFUNlJmTDNCRk1nTGY4WktKZ0V5WUJwbk5QR1BONFdpa0hBaHQ3UTYzVmpw
        eDJUQUdnOWtFakozOU55SFFQOFJLQlBoME5idmU5V2gzRmlzbFR3bUJDVTB2T25i
        QUVvTVo5S0FuLysxSk82cjNPcGNFUFZlbWtDRlhRVWYyMlcyYWFiYXNRMGl4TXZB
        U1RBelVjem1rQlZFcFNTa0Z5MVFXOXl5UzkvY3FIS08vZEc4V3o4MC9SRmhFSk1S
        a2IxbmRNRkhJZnp0RkY1OW9pNGlMY0ZMREllcytpZm92aHdJbFFoZmZCZWphWU9G
        bUIyVWZqdlFLREZjV0xFbVBGMzZibUczS2t3SnNQWEc3bmUzaE1ZdmlSQlI5dEpn
        RjlnTEU1QkJLcUtVdmRNMGRtTDZPOXNMRS83NHZ2OW5Id2VYbEEwYm5vNTdOdEwz
        RndXMEVGYkZTZW5WSi9uN0ptQ09DaXVIYk5odFdWMVJkZFRlQmdWN0l1Uk9QbGdM
        MWxMbWptRlVVb2JhLzk0TExRQmY5c2ZFK1c0V1N2VC9ZTDVmTlV5NEhKMzdIeUtJ
        UjBPWDNSeFZJY1JXL2hseDNXM3BjV1RDSnViOUhIeGdmTU83R0VWKy81NElJWXZT
        QlloU1Z3SzZINjd1K2tHRjY2NjNvdHByUHVyeFJ4NzVGdHF6R3hCYlAxdXJkUElO
        ZmUxeW9Bc2dZaVhWZ216eFU2bEJ4eFJlbHJQUTQwL3hnQlBPMkh2cnFZL3lINkdj
        SkowSTIvYk5BNHhOekMwemJ6TmRjeUZUNW9FY1RPVVhLaEsrYXMzVnBHZVhJeW93
        bWF2bDU5VDMxNEZHWjBUZGFpdlpqekU4RkgzcGIwWHA0SGlaQ1gvSytreWhQbmN4
        QmlBR3lkNFNmZnIxUFdmRG9CVFh5UnlsakFPL2laOGhpMkI4bXhKNDRqMkJQazVt
        MlZHVzQ2eUsyblJlVW5lZm9qOGNIelV0VXBVeENVY29UVDd3Y2haYlVmNWJTQysz
        Mk9pRTlvdytwcUkrdDAyeHpVMXpYUUpPeHFCaXgxSU80ZExGMW9maEVpV0VSQkIw
        THFIRHdQaEF4d05RdXRyVXM3K1RHcEFJNS9DdThBaE81RHFpRTdncmoxT0VMVWZr
        WUZHRTRTa0hiMG5XaWRzZDFhcW9Qd0lJK2FWUS9SQ09DcnpjSFhyWGtiYUlobUhN
        THV4Nmt2T2JsN0pxNnlCMExNbkVBZlJkM0tNMFlUN3g2clpuWDlDM0NVb1lPay9o
        K013Nm5pNFE1RXBxU0MwOGNGWkRuaFpodzMrUVhuVU92STNKNG4wS0FLVlRrWDhj
        L1pyY0crWGN1WmlKK2tZVW81clBFOTVvK25DSG5Nc2ZHRUFaM1RxTUE5TkJQb0NP
        WTRVdjVqSHIrWkZvUVQ1Uk9MN09LbmFscmRJMUxRbUtYNjErYStzc1Yxa2ZXQm5t
        R3lIKytVaUpad3V5UExtd2NZSG1YelhzUjN6UlR6ZzVVckVhN1UxVktPREExT21v
        cXF3ME1aZFkzVTFqT3VjclQ0ZWVPRHdLV1Y1VUtNZG1YYVBMRit3UW1uWmFmWjBP
        NTFuWHA5cXc5akJqanBNODhQYUZ4TEVpU0NZTERNaHlvS0h4YjI2WWVnQzJHWnRT
        Ui9aemRURjk2VWowRFpOR1dDMk9YUS9PZlVVUFJJZkVOMGJQYjhYZkxwSTQwbkZJ
        ZnI1QWxKNm5EVU42bDYrdDQzL1lPNnNlRHM3ZUdYWWdTSkU1MXRoQmNUZ1NBaDdI
        eWFESXRiMUpGMVh3TFhxSlE0YWQvaEN2OStQb0lQY1R3angwZ1htRkVMRElzVWJq
        ZXQ1TUhPZVdLVGtpWWtsUHdYU1paUXNMSmUzV0JxYjF1RzloR1pXekRLTldtUmpk
        U2xiaDlQaXlTVllCRzIvRG5EVlh3MDd5OGZ5V3FKZStUOGE0SzBZWHozVzdTdwpB
        RHgvZVlyVmUzb3dQVkJvNy9TbVVLaUt6cllYanJQUXEzcnlzWFFCbEdnCi0tLSBN
        YUFBQlkwckM1Wm93UFU1K1RFd2VmN04ySC9LNTVsT2xURzY3SjJTTFZNCuFCndAY
        NHV08YyQsZWU4rrQOmpklvokcKtHZcc6ai1JD88orzIg0LOEacchPO3qoNOmsdvN
        s/ChkwjM5Zz+QfA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:SOOnY60CuMo6LN4FoczWDRbliyMfiuR3Z+5+JWlyF9UHjpfTufOmFmbpxzlnAEdobT6kuwTpL6Mjh6xPfbkTaMJi3BFwT70ij64qaSY2+VjQXIAYZKXIkeBFXQxqAI2wwgvmFSTZ0I8KbEb+onQsZHaBKeRBvMwawHfqZpxgKhY=,iv:azWjspM8Ekr8YCP1UelG44PQXjUBtMjHIXvubm4JhFQ=,tag:AZTcYcVziRLHb0bZjt35iw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.1
