apiVersion: v1
kind: Secret
metadata:
  name: atuin-secrets
stringData:
  ATUIN_DB_USERNAME: ENC[AES256_GCM,data:azOphEo=,iv:M3/XHgy2jVJGBSHXiopPbULmJsVxfSguRbn2O341jOA=,tag:JFnmPkMbHrY5APpjbvNMww==,type:str]
  ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:MMAfxto/vD66+DJHR9uVcJiyGI87M0uHAYac653ZqRs=,iv:REz6mX0mclNCQVRQ0rLIURxbApj204MRy/Z/OsCzU1I=,tag:DoEKs6KZ99FaJusyxFXvzA==,type:str]
  ATUIN_DB_URI: ENC[AES256_GCM,data:r4rI5o3KRvp8H5zx98i16SRb74fYak5cpWn8QHktgtZKU5jqsxFyjIGeBw0FGwc2M0Ek9oltiYrsewdh4yDvF+qJ52ib2A==,iv:wozGzEEHIhfhhA9EKHs7L+UKSF9c681BhvfdsaOFOI0=,tag:zp1o44bcU1cf2W24TuaBqQ==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEE4Ni9kU3dI
        SmYvZzkyd3FFemUvbHdKQ2JlMklOaWViRnBQK0QrWm1Ib3I0d3BSZGJRem11aEZz
        TDd0bmMyQll5Sll5UjhVY21tU2VuNFo5Y0ExOEplZHRvSE52Y0FtWDRzZ0oyQk9v
        KzhlU2dIRlVJc2pvQ1ZKblJnUGtJZVpyem90bE9xT0d0REE3aUgxczdhUzZScXJE
        WEkwRERkdmpzM3R6SzJlVUFPazRzVktRUmh2cksrUzVNWHRzZTA1UEtwR2hTT2Z2
        OW1QdlZLU1RDVEFuUi9aSEkzblJwODRDTlh3ZWdRTzRVTVhKNGNLMFpabHF2WDVz
        YUJLRHVZcTdmZXF3TnJVZUh6YXd5QkpVNlVvY1kwMm5JcTczRVR3Rjc2bTJ4WE9R
        RE03WkczNU5KUTZXNVhNZjZBMkE5OVRqSXJxalRoeCtxNFloSkNnTWVLZnZ2UzlC
        ZTBBTU9mb21SdFRrWXRPbGZmVzNlc3Rzd3hKaUx3eTFHQng2RTVJc2ppU2F1cSsx
        cVpNdmVaVVlES0hCWjlGUzJnclpmdXp3TWNORXo5SnF2YXAzSzVXY0xKSlpzMW5y
        Q2g5Yk9IelFTVmpLZTVYQkhRaFpyZktXMkxqbm9VWXNiVElvRnRneGxMeDJ3V0E0
        dmhtRk9sTFhKUGYzRlZ2UVNvVjNxZnlZRFNSU2FXWmRLUkgzbDRnSjNtbitGUUdh
        UDY5M09LSUNxWUVqS1V1MlkycUxVVXFxYmtvUkxOUVVIcWQ5ZFRWVzBwSXBwd0oz
        cktWanNjVlhrTDB5NlJXcFNxWkhpL2xLR05VMHdOaGNBQ1Irbm9Vd2JmakFib3Zo
        SlNocXl1VTUxSWZSc081L250c3dmMEdsZ1RoNGpybVptZld4bFdST1hSM0lFUlRB
        QnJDbWpGajlDWEJZVHEwb3dXRVNWVElVc2JMcDlxT0FNSjdUYWtlc1d3alhrelph
        bU1Wc3llTGNBdWhvWFB5TVFGTTNUZWJmV1pIWUM1eEJORWJyZDlMR3lwTVRQbFV5
        SEZQdGdQVCtSTCtPbnpRcGUrbldKT1A5MnJzeGNQbmc2elRicldhVGdhNjJpUDhp
        c2FGcWw4S2ViQmFVMzgxNUVKN3A5NkhvNDNiSWRsT0pxZnE2S21MTHlMc3Y5aGI0
        ZGlycm1DWUwwM0ZYRVFaOGlERzYvWW1FYUhFck5IYmxKSDZDUmVzNlJvbVNpQ1pw
        WjJCY2VudWRyVHZRVFV0d2t4WW5EMU00RGdrbjJxQjc1NGhFT0RQd243elpiMU51
        dHcrN01SWkJHa3NIT092d0hCejdpeGdZbGVER0c3dUxtcVhlbGl5UnZDMUhlNFR5
        Q1pmQWpySFVsRUZnOTRDUGhzODEwNm9VMS9Qd1JMQmd0dFBmZEhYQjlPV1NCLzlI
        bTE0eHNuemthN3FrSTQzWlVZbTEyVjBscDNkZzNtV3dDZEtRQitnSWVsSzZ0Q3hQ
        ZUorWGl3Z2JOS1JqWG01ZGcwZ3NoOHBTK2FnVHJuQXZ1VXdNSEJIaFZpanFyNURn
        TTduS2NrM1h2M3VVbnlWMHJuek5SU3cycTZNYmxUeGE2U2V4ZDBKNlBITENPeWNB
        alAwa2hzVTRLRlJJYnBFd290ejAzZnV3c21CRHBwZVpMMmpjZWppd3l0N0dtamRT
        eEpMS3NtcVRWVm04dFJWQkJWWEk4QzBPV1pHUEtVRkRWWVFyRHNEdzdhSjc2dDVq
        MGMxd0F3eGFHQ3JCR0tRMjBFb3ZINXQxRkR4TzlWY1R0WjQ1c3BjTUlud3hqMmdN
        Y3l4VndnOURab2UrQktjak5YMEI3bnNoS1hjSktDb3dLdVU2MHlIVklHU203Kzdy
        TW9UYmx1NmNscVI2TXBmL2czNmNTbzNtaGU3clRweXhqcDhYZGFDbTdlSW5ia0F3
        OEREZ2pONEFyc1VEYTN0L3JWNElaaWdmYS9pVzdFMDVuUmNqNmZpSlFDbk1iQQpG
        MTBsWVpmVnF2bmcwLzMvUnBGeGljc3lzVjgrOVBGK1FnOXI2UFlkYnRVCi0tLSBw
        ZlVRNmZ4Yk5RZVFYeVZwWEVPeTFhdVBKZ0NPWHlxanpNZ2NHMXllZmlVChD2vBeF
        +YnbCyQ4cakY098qgW1vrAiwgOJzXEx5WTx9G4rpVzn21aYl8iswliO2OjBsTvJx
        9J3GCrPSYXUnlWk=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:86ffzUXKXigdzzlncbu38J6Yt6pudO2OQyNVHzeN8LmahcOdj+k6mFjHisIC5v5r1NUUAODsoziyT152wJd62hhBCOkCN3omWv+w/aGtIMjV16Vz3KdtPQLUVrGaC5S/5Tups96mgsgsGpQ5bNh4quPe3EFkzVc/Ai34RV7EALI=,iv:k3ICqgtITcjALLFqU1SAmBSH7GoDhz3hQA82qSX2MIw=,tag:VaVLxcb8JI4Z9k3BaslGvw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.10.2
