apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
spec:
  interval: 1h
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: filebrowser
        image: ghcr.io/gtsteffaniak/filebrowser:1.2.2-stable@sha256:0e8f0841fe731ef82db285af510e61fed7ad0a7622bf8d39ca6f3492930f8b58
        volumeMounts:
          - name: filebrowser-data
            mountPath: /data
          - name: filebrowser-config
            mountPath: /home/filebrowser/data/config.yaml
            subPath: config.yaml
        volumes:
          - name: filebrowser-data
            persistentVolumeClaim:
              claimName: filebrowser-data
          - name: filebrowser-config
            secret:
              secretName: filebrowser-config
        service: 8080
        ingress:
          domain: files.cocointhe.cloud
        pvc:
          - filebrowser-data
