apiVersion: v1
kind: Secret
metadata:
  name: garmin-config
stringData:
  values.yaml: ENC[AES256_GCM,data:ZNpaAI0sleSPh8EQ1lTByyMEdA1/SCjrpDHLxNCWcjVke5jusbGnQ3udQXbNPGSZGQerC+mIbXW5OT1HoKwQCDpx9oYc4DjJIeD8ijNmXMiyCT4OtvOO6htf0ZzgJ20P2HRyJp5ThcXwSnS49SMSEnhWJrkSmhtYV2ORJdmPIX6ruXdn6+Qdj30HJTdHnTdGmSF9KakXMuluU+5rfCBFMkoGdc9WJGj1auSRTTbYkblDbYYrbPGg4lHQAPzoXFjaI6u6R/YShpZBmjRgDpbNDbzXGyNtNoSOJKXRYlBg7Jv2Oy4R/fRpoaUTeOqluFYT/Z/6rVSDbB+kPE9o7WOjEyUq,iv:xj9Ym/Y1114gbpSSNQ4AknkfyZdBwtW1xvEayHoqFX8=,tag:rokKNoYkeFMwz5XeRhZwxA==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGdmRFk3RzBL
        azg2YWpTUmJ0SlhkVFlGSmRIdVMrMlhydG5IeEVGWUJPSjlkUURScVd0M1VOd0RX
        VGxiRk9qS2hJQVYyNlBUdGpGb0wxUHB3RFdRejBKYU83YzMrRHY1TVZ2ZXllTGF5
        YUxOMVpIYjBPNjh3Q0xKVkpkMGxMQ09Lc2ZpS2l5TWFWbHJQalZSaW9Hc0NHYTRp
        NUFYYWU3cVV2RGN6U245a1RMVUZhb293bmF1MlNITU5FRXZpSVd0MkMrYVdnb2ww
        R1ZvMEpZVzJLSDQ1cDFkNElXNVkwTGdsYlA0U3lqdFlObTI5dWk3S2hJajQ5Z3BK
        amFJLzBSSkpubjEySFlSNFpmN0I0dTdkdG1hSURKNmFhWGZCcFJWOGtyaEJuUWl5
        MmJxY25GSVBhTitJSTNicGtLS0Y0UnFVd01DUVlPeGF0eUdUNDdpS1lpVE5zRnR5
        QkhyM2V6OXZVdXMzMHg2ZTYwWVk2ZFEybUZSSDBucmxTaXBaZmIvdlhnNWl6dkhT
        d3Rzd1h3bThPOXA1U0N5b3ErUjYyWXB0dDlMcVFqM0xPS3QyekV1RGVZb0xRcG5D
        UUZGc1pmMklFS1RveWw3NWVnNmVPNzhBRGJHaGJnd1VjZkc0dytFNXdGWXkrVEFt
        Z3llcWVmVllqdlV2a1FZdjE0ckxSSGxJVUJVSkg5YzJSTE1KOTBKWjZTWG5rcVZB
        aFFJM3NzSk1jNmRkREFBU0JvT3BCdEduZDdmTDFLaWlpUUNWTVNNckN5S1l2Qktz
        WENTa09KZ0RtVmRBRlNvWU5IYllaWW9XdW41RmhlMVpQU3cyVnA5a2xZNjZaUENa
        NUg2SVNGdTgyTjJoQWR3aDJpS2JGQ3Z2ZURQUlRFZ0lGNmlZbUFWamVBdzAyRkN2
        N28rT2VGMmVtWTVtUHhZQUFPNTd1ajlBbkRSdERna01nZ3BBRTVObXVzd1kxWkpt
        VTJzSU9MTGpITUY5akZUbHRzQS84Mk1zcVZRZ3pPQXNzMWlodm54NllmQ2dpUzZE
        SDYzQzBxdGJOTVZJYkxyNUxqUEpsbWhPRis3S1NWTTQ2bVJXUkcyaGlPeHM5Zitj
        WTVVZmhGYkE2RlZBTi94RVJlRWhHbFhrOW5DMWR3NkxQY2hjLzJqVlFFTVZmcStM
        WjNDMVpXbDZoZkFNb2ZaOWRKaTRLRERVaCtIM0tsaEczdGtabDZicEw2blBwUzQw
        TU9SVEVzdzNvMFluTVpxN2J5V1czRytmSWZONnY2NzllSFNyaUxZamwrNlBCNDZQ
        L1dXQnJVajNXbkFwazdyZThTOGdybStxYU05K3h1bHVTVEVFeG15ZksvSTZYY3dU
        aTVlZ2hodDFwcmxBSG5qUzRSMEZJaDdjTXpBUmlnNk85RFF4djFKWHJzdGpSaGdn
        U2FteXBlTkdwaVNTcWw1OW1BRjZScFZMQmxQNHlLNlFlUmFLT21DSEVhMzBka1cy
        QnljZDVNZ055Y2c5U2dHbGFCTXFoSUxwTHRHU2ZyQ2lKdVN3Q2c3NldDU1lDNXgr
        S0dacnM5MDFIMGRGaEVGU0lma09tU1RtRDdINUJCYnUxUzF3eDBOVkVZaDdLV1ow
        WDc1dnNyV2dmSzNVZEF3bkFGT3JKWVFMMkVJbWhZU1owYi9UVWZSK3p4R0dSS3JJ
        YTNYeWQ1Q0FlckJhTmRRbmMvYW5YbmhjRG1kM1IyM2oxOUt2OWdKZVp1VlIrdEx2
        TVZya3l5RjYzREEzYXZHNktkdzdrYWdsanBET0p0NGZib3dZYWc1ZDl5YjZxUXc5
        OVQ2VlZJUTFHU0FkUmo3VmtjM0w3TDlJa1M1YkVTdk1BR3NnbXZpdkRuV0YwK0pH
        c1RtOVVKSDBtSkFadkhqRlplTlRMWHBnUFYzbWFpVzhzMVh4MHNVRk9leCthcEg3
        T2xTeUd2cGxDMmNlSVF0TWhDcnZZejV1NDlUc3Z3N2RzbGd5VERFck1Fa0NNUQp6
        YTh4MW1XWGxReTRkMFkxcmE1ZXR2N0ZneXVlTm9XYW1TODVqZ1FVak80Ci0tLSBx
        RDU5WGFDdUpNZjN5azhSbG0vVi9tdE9jdHcvWjBvNGRRdGU2TW90ZGNnCu9uNuiA
        Ykgpmk/s84Spz4emPw/EK1TW+lvEZJqFSqMz3t90+2EAWKEUKfBxKWPGzWvpS8rs
        uJeSTiI1uOpMZr8=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:U7WeYfVn/gO3TrigFYElqwy3/Sb2nimEMoL5jTOp4LDc8jdknzYg/0HJrIP+4SPDHucbL07YqJ831G6Ydg8/pGrJtE0PD4X0TuzPXtUcf+R4P68HV1qmPH9qyKINOenNGHYht5GyUyGbb00OtAJvwmbRLF0b/PHhZQG/1dnRh7E=,iv:Xy/7EQUy4ixTs2BIc/RC2cRYEnmBN3WMKK3cT47GdXA=,tag:lzfJwgZjsW+LHpDo+EDjEQ==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.1
