apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
spec:
  interval: 24h
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 1h
  values:
    apps:
      - name: gitea
        image: gitea/gitea:1.26.0-rootless@sha256:9bfff178f12373bd7d64fc90b7a59bb0308cfcd599edd373d5714e3617f0c54d
        service: 3000
        deploymentSpec:
          strategy:
            type: Recreate
        ingress:
          domain: gitea.cocointhe.cloud
        env:
          - name: GITEA_RUNNER_REGISTRATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitea-ci-token
                key: token
        pvc:
          - gitea-data
          - gitea-conf
        volumeMounts:
          - name: gitea-data
            mountPath: /var/lib/gitea
          - name: gitea-conf
            mountPath: /etc/gitea
        volumes:
          - name: gitea-data
            persistentVolumeClaim:
              claimName: gitea-data
          - name: gitea-conf
            persistentVolumeClaim:
              claimName: gitea-conf
      - name: runner
        podSpec:
          hostname: act-runner
        image: gitea/act_runner:0.3.1-dind-rootless@sha256:a7acab303ccc0d477b4346cb6b0dc058eba22cccb21a5a463ddcb0477527eaad # renovate: ignore
        env:
          - name: GITEA_INSTANCE_URL
            value: "http://gitea:3000"
          # - name: GITEA_RUNNER_LABELS
          #   value: "ubuntu-latest:host"
          - name: DOCKER_HOST
            value: "unix:///var/run/user/1000/docker.sock"
          - name: GITEA_RUNNER_REGISTRATION_TOKEN
            valueFrom:
              secretKeyRef:
                name: gitea-ci-token
                key: token
        containerSpec:
          securityContext:
            privileged: true
        pvc:
          - runner-data
        volumeMounts:
          - name: runner-data
            mountPath: /data
        volumes:
          - name: runner-data
            persistentVolumeClaim:
              claimName: runner-data
