apiVersion: v1
kind: Secret
metadata:
  name: immich-config
stringData:
  REDIS_HOSTNAME: ENC[AES256_GCM,data:K0t9KawvgiCrg9deIA==,iv:TQV4fcMNSvhu/ymV7sYBUf+up23wdfLWfKJikdAcSDw=,tag:3Fdc8z+6ADkuozdlYCidQQ==,type:str]
  DB_HOSTNAME: ENC[AES256_GCM,data:nc6CNtZGjQveddXJKM1/,iv:UJd3JxDzUGt1W5ys9L6iL9FFUC2yOlvmyUVCoknXmEY=,tag:OFBbmTYPZoa2D6rBFGqihw==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:YOCGPAOh,iv:thFnGTjeppFaMEeqB31OPkkOMENpEk7VZ0P9btsUtX0=,tag:9Kt7JYWrPxQyvgVysojJSg==,type:str]
  DB_DATABASE_NAME: ENC[AES256_GCM,data:Aoiv8ztS,iv:InUkg4anqKBj+o5XwXuA9O5N8ms732p3fTKu0G3gDRI=,tag:wbuNkkZbv7qJuv8onIy4ng==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:X5/KGgfv,iv:BD8HUQUVQDbRREj2g/AOXleI6c6GARzHq8OwwD2h7SA=,tag:GrVxVyGKNO+mdzVGcgmEew==,type:str]
  IMMICH_HOST: ENC[AES256_GCM,data:C8UKeDI/Mg==,iv:/s/4GqaSU2gqrZRQKWZWQk/ufj82UPGIRI8YIEL+Ev8=,tag:lTmY6IPzJ4k2pdfTUFaBug==,type:str]
  IMMICH_MACHINE_LEARNING_URL: ENC[AES256_GCM,data:zmv8LsWyOApcwmAHP9+YB6R/yqVV1fe/4E68H3XiOLInAKg=,iv:jVc76eldDwXBzaL1Jhf4CEnXKkqGGr8wLsz8KrH7T9U=,tag:bSDzeklk6BOU068YjkwAcw==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEZ6YnNlV2lx
        M3lkUE5BYW1TSVllazBhZ0w4dWxFQWV1eDcvdnRheEpnejFWdDhDQ05Qa3pia21R
        UjcwTkQxRHUvZmZaWG1ZeVFsT3ZpNUxDc2tGbWVQQ1Q2Y0ZIZmNBVHloYTJiZ0hl
        OG9kc1NXNWZXbGYrN0RtNFRrRmhMM3FpSmRrYjZqZjFwZzI2RHJYeFF2VVVweTNR
        OXJpRWY2cHpFeXVFeWdVVEo0VldHdDRNcmY0Vng0N1ltMXZqYUIzV3NaNGkzeTkx
        a0pxQkdoRVFBUDMwT3lpUmp0MlpYK1U0dzRPN0ZQTUprRE9QM2RqaEFMYlJac28w
        a21EQldUOWJyd0VTcnBreEhwbElzclg1OVMvRGhpTjBtdEJZMEZDUGhuaWJoR3Nn
        NXVXK2l6Q21ZdEdOSzNyVVd6VzFRVjdUbmJmZ3preGUxZzhCeCtpcjdzZVhzcUpD
        L0FJMmV4K0oxcGV5Ujh0WWwyS3VheGdXRjdQUEUvM3BHL0praE1kaklIQUFzK3N5
        a0YzcXY3MXowNjNFaEVPbUdxOUNVRnBNMXRMQUpCRStCU0JlTnhIVDNzU0J6ZUJE
        UEZLSDAySURRcW1HdEhSUlpLNVJaRFJneWFIbko5OFYzcHFuWi82UCs4UGF3KzBL
        OXFPTjNsdEhjdUE2WVBLWWo3Y3FtTDhHR0NwRHR3bkxvOFo3Y0k3SW9JWllUWDJY
        K1FQN0NZTHoxRldTOGNnSmZ2Z0lEcGlzNTR4N0xCdHJIWmN6aHF4aHU0MkhSc2d2
        c1RiNGJ3WmxxK2QvaUJXZXJEQ1gwMXRkS0FiT0xmRmNLcHdGejh0WnpzSWxuZkpC
        blBNZk1sdVZjQnBrQkFqWkhoa2pWUlU5OHIvdlhoYU5oaDUrdTBLbVR0b3VZYm5o
        MDRVVEhOTFlHYzhXd1l3RlU4MjRodWJnSnEveFRQU1h5UENtSkRTN1JPYlc3L21z
        NXdEdXpyTnFMVGlYQmNsblBGNEJ2T0JXakNJenRGbnJ4blpiZ1FaSkdadXZ6VDEz
        bHBXVGxNeTlFWWlyTHVQNUpvTExKVTU1dnd2cHhjdXVSL0FLR1pJRFhtUWV3OGE5
        bXJhVzJIc0R2dE1vTk9kVUNmN1FIamxqdy9WWFZyM0xNWXVVSDRjQ3hvMk5TUlNJ
        VWlRM08yYWZuY3VFYTBOMWRzZmd2ZWFYdkZzN0dKS29uSWlnNTROcy85QloxeFp0
        bjU0a3dpZ09FQjNCTC9VMndtNDd2ZzhXbE5ydUFXNkRxUmVyUDhITXFiSWY3bnNo
        RE1BNjRSRitrblVNYlU2MzNEdUdncWwyVlFNZTFGVlJ5OW1NR2swb3VqbW94bElw
        dTBQdXJ1UjBpUXdjMWd0M0t0TmlCc2EyZisra0JKQi9QdUZ3RFBZcXNYTXNqMWlS
        Q05Jd0hGVElJMmowMnFud2E0ZHE3Qzl0U3dTbzNUZFJ5TGd4NTRxZFpNRncyckxq
        R2prakxYYjcvbFJKRjREbjEzc0IzbXhmS0wrTUhVTmdOWWo0T09zMVFQUEMraVRZ
        d3M5SzRXblNiRDR0b0l4Nk1QbXM4ZThDbERWbXV2RWV0TWlXZ1ZoUmNHdzJOREJw
        YnlMaWFQNjNTRkc4cGZvYVBKOFBOMUNKQVFua3NXRjU1UXljM0hOOWx4TFA1L3BX
        dURIKzZsOHVjUXpSQUNGTFdBNXRxamFSQWZVZDY3Sit4VkhjaERxT3FUMFdaWlZ2
        WHh6bktVbXZxNHpwWmdOQm0wdkdUdU1oaDYrNG1wb3NVUk80azY4WUJrcWw2VTJ1
        blpQeXZncHhLNm1nS2JjS21OZjBkY2ltN3FJckU5aXk0RnIzYlVtWjZ0QWVQeTJl
        b3hoTzMzeHNyUGxGWmFwS0dUOUFobDVScGFZb1BWWHhlQ0h3a2hBaVVManlleitE
        eDlaWEU4WVRhYVJtL2xGS0wwQ0JaUFVoMEdPeC9BZ1l0R2JiQ2h4YS9MNFdUQQo1
        aXNKZ24rWTFOQXRBQUI2UTd1NGl4WFBmaHpRS084UVUxYjl2dnhxSjJzCi0tLSBw
        Q2dCdVF2Wk1PNGwyN3NpTThVelBTSlRrbGdLS1ZyVDZpNmYwdGg1N2hrCrBh6qSm
        YoBWDx1Z+GuKnWjsKos1x8CRUg168LhkSSIwc4tuQcX4KYGRLxXLt1hZfOTvJPgs
        +2j/fiztfO8hqp4=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:F8fEiF20Nqo7TAVSdcw4JMdAK0WY6H0TpT6mVy9XZm8A31oaFHzlbdVTUf0MiJOFLyMaXNZSfJDhVuq0IBUUYvFJ2Nim3923BdfkBHWX2f3fafUSZGGH6Y5cFzO94Sa0wFxB1owy2JT4oAFBpYJOB0l0hQXoPZROuquuSyCuMak=,iv:RYc33Xv/lGBT8jKwNRsqyyDQ8LlVDDL1JX7xUhqbIIY=,tag:LYwN1ekj979o3ykDUOOa+Q==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.11.0
