apiVersion: v1
stringData:
  PAPERLESS_APPS: ENC[AES256_GCM,data:m8pek/tUy3vmgPxlzYGwKYl3JStJYai5BLXTcuRpbOY5dt0iACWFmbBDGLigsw==,iv:ruKFfTd5ojvZY1n4iFp+tv4XdNJb+BhG8DxwEc/oqTM=,tag:dAj2kz4HXzDkdZlI2LeTmg==,type:str]
  PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:DGLqKPt1sUj1P5UdcJONjTWMb9mi4H/8gjHQJwouzNLbL5xfas9xUORYWstvz2Zs9uutsbeAEHFUJEXkw5vNnPfdVzEEzMjSHIaATmH8ZwLVcKmZXayzEyn93Hxtr6RRhA4q9dOKycZCqgwEU/8Vx9oCHPucz8PSbVpJHf4Ga3d2YhkI9Hr9K1ei3y7eqpB9egFh05CqaHLUTZyaBrhr61oCjWn6Z1sp22K7Lv7XxA3BXHt/nfYmFykgg0Ey8I/M+2cFA1nVLRb2sdi1XFsxjn+1RbXx/MZ8LXPTFsNOKiGwiiL0oFqkRUvYlOsZMkyqkzz5YC3kTAqgn5lVMdAPLSBaCIHLBTAXq7Q21N6IhOhmCQcVjd4q5JEXvxKDOJcRpvgvk9gzoA==,iv:V4pjHzU8u3rTHKqoTHcQkQ9pt0sxg+4to4zKww6sTlo=,tag:KhKrteCoMiBbzQD8oRkPJQ==,type:str]
kind: Secret
metadata:
  name: paperless-oidc-config
type: Opaque
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFlqUTRJb01H
        TStpdmdsK2hlV2dPTGFaaU43WHRBdmROVUxDZU5zWDQzN3lnSnFQbmN1NzB1Yi9o
        R1ZJbXBUdlBKSEx5Ry9GMXFPSlI1S2VUOWI2NEZkUXhCZitPYUtjMS8yOFdhYVhy
        UHBPTXJnN0JFQkhrd3lGV2FKR0pNdnFSRXhaZWpBRHJocDR2WmxpeXhoQlZjTGJ0
        TkY4elRiaFVXNU1YeWVQTk9UOXhDY0hJejltcW5oUXhXZCt1czltU0sreitjZ0Yw
        OGYyZ3BUeThtcG9QU3lrVnhrODBjblg5Z1pWRmxLNjY1dVljYmFJNzVWZGxIdkJR
        RitwdmpQbGNVOXhmUTFuNWRySmcxWlNsRTRRRWxpeEd4SjBCUFlqL2dVUmJXTjJH
        NDZxaVBTVlJnSGRGVFl6MXhOV0lCR25ZNmNZUTRkSU5VRWMybFF0VmZteEt6UklI
        ZmR2MzFXWGJ2a3BtZnhGaWZMa0YxSkVFSXJmZURvRE9ZemhYQnE0MnVCRkplOGNq
        Wm96MGJiNDJnM0g3SjFrV2k5Tmd6My9TSjdDYnF3Mi9qTXZwczdqc2U0NGVRSEJk
        QVpWSWNaRUhuMU1RTkhQK3FDZG9iZlZkNm9FSlJzS1lXZ3NnS09Pdy9HSHE0QStN
        SFlFV3ZETkc5SUdqSTROL01kdkhMNVIxcTFMTTBxakdjcmU0dDJLdXVPdFNyb3Vo
        ZkpwRzErQjJwNzVyck5JRWdUMGx6UTlIdkI5NTRidE90d2oway9YWUxvdXpRR0hv
        ZmVQckZ0YlI1RFd0bHdpY0RGYVZ1RmFpK2NUeGROeTQ2S3NiVUtLTTNTMlBBdnRq
        a1EvOERrS1I4aThrazdGaHVIdzBqV0Nya0d4RlpQQjBhaUpUN0NoRGlZTER4b29N
        S3pKNUVoQ1l4emlUVlVwcTZMMU9SOTl4NUxhd2c4bXcyS0VZekhpQ0t4bmhvWjVs
        V1M4RGYweUg5OFppRmVKa1V6eFRWbmc4L0VkQTI2VDB3c244dDVsenFIY0dhM0J0
        alI0TU1NZW54TlhZdXlsSnU1VHo0S0NzcmhjZFRuN3NselptTkgvcnpzT0VIY2JZ
        bkMrTDluMHRpNXNmallXeDhObHpBQ0FOYVFBQUNSbWNuQlNHaVRSVDFjRnZWVDZ4
        aVJ6bHhsVmhMckRKS05yUWo1ZTZQSG5ZQlJTUUdSRmZZSnNNL1YvN0Q0U3U3R3p0
        T25oeDVjLzAxK2hHSkNMa3h3ckZWTkw0OTBxdUI1WUtXRjJpdzhMRExpdk0yTHpw
        V2czc3NSOW1hY1BrNkVua2F1TmIvVWxISmtmK21mSE1QajZZZHNLdmhuYUZwdDlO
        UEJoVGxoOWMxdnpCYVo1LzVLc0hOSHRydmFYalRkS3liNWFXNzUwSGtLb1RabklV
        U2JoL01MMHY5M2ZOekJXT2ZWV3hFKzVwdDM4OTVmejh1emg4VStZUHZrZWdjRENm
        TlNobEU3K3c0V3hkOEdEeGlLSzlYbGs5OVZJZXpZbTJJQXVOUXZpMzhTVXR1M2Zy
        K092TkltT1BwM3ZCUDdkZC9HeDJoNFphMW5qL3liOVViVlRiNXMwL3lZQjRaQ1lU
        d1h3MlhTZzNQTVFLRUZXRk5LS3pkcE1aeURWdE1OMGp3ays3QWxQem8reTRoOTY2
        NEFXdk1PS2xIVUoyV3RGQ1EraTg2enYxSGFNdDc3WHZla1V1alJmOHlXSnB3eENH
        NTNsMkJPbGFTdy92R0dLWEs1b3YrdkhaNHJCdXdjRWNNZW5pc1VOQlZJcWFTemNx
        QXZXOHhJOHQ0Y3J5ZGtJa1hpRys0a3Jhbk93NndRbkw2ejVETkt2SEdEVFRxK0ZZ
        anU4UWxmZHJwSXRsWFRUb1V5QVJ5SEIwdHhXYmt4NUdVQUVMUHY4bWVXY0Jhc29t
        K090Wkg3ZHYyUkJwOGZQZXZLNjU1S29idUVhaDFxVEhJQlVldTJJMGJxYlRWQQpJ
        RUdCN1dwenI5Qmt2L05uL2ZVU3F1NEZNWXdsOUc3c1Q0b01za041RFNvCi0tLSBM
        OEsvSGE4VzRzOCtBemtyb3VubTlRU2FsaGtNUFAwZTE4c2dUdXVVQVAwCvbsxBUd
        HzbSt6DFT6cDN21wD8Jq0WmbCtmVE3YRl9vvQlfR7O7D1x3LJZFw0UXnledJjppU
        LIeqIbw5urw7YZA=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:Cqz0566DzhV0tqyhnkK8hvhXHeRpScQTcwg2NE9oUtwfpBwZiIYtqkPKCrA2PHV0KZC14A+ipZgefaCvccZ1SmK8FRcm6WAhjtVPEn4ZgDpya9KL0hP09FHhVWVgyyjGGf5pkRyLQG2Rrjjlx7pdLCICeodz9AfhQYpFXNIokp0=,iv:cPZR8Qr5L79jaB9WxnrT3Co3TOPIZcuE4ducGg4+ZPU=,tag:PEFBNTZjwUe2XItmdqaSSA==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$)
  version: 3.10.2
