apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: pocket-id
        image: ghcr.io/pocket-id/pocket-id:v2.6.0@sha256:6f030eabf082365109bc71376523399d17f1fdbb4d3cd7db852e23767d5a5eb3
        volumeMounts:
          - name: pocketid-data
            mountPath: /app/data
        containerSpec:
          envFrom:
            - secretRef:
                name: pocket-id-config
        volumes:
          - name: pocketid-data
            persistentVolumeClaim:
              claimName: pocketid-data
        service: 1411
        ingress:
          domain: pocketid.cocointhe.cloud
          public: true
        pvc:
          - pocketid-data
