apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 20 * * *"
  timeZone: "Europe/Paris"
  # suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: renovate-cache
            persistentVolumeClaim:
              claimName: renovate-cache
          containers:
            - name: renovate
              image: renovate/renovate:43.104.10@sha256:70ba2f1c47212217dcb0fb6e27f43143c6175b262138c53947328fe9ab5d45a7
              args:
                - k0rventen/lampone
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
              - mountPath: "/tmp/renovate"
                name: renovate-cache
          restartPolicy: Never

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi