apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: "0 20 * * *"
  timeZone: "Europe/Paris"
  # suspend: true
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: renovate-cache
            persistentVolumeClaim:
              claimName: renovate-cache
          containers:
            - name: renovate
              image: renovate/renovate:43.102.8@sha256:e230599b399a3ed960987fe652550e39cd4f514dbe9a693839da1b99f049a0e1
              args:
                - k0rventen/lampone
              envFrom:
                - secretRef:
                    name: renovate-env
              volumeMounts:
              - mountPath: "/tmp/renovate"
                name: renovate-cache
          restartPolicy: Never

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: renovate-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi