apiVersion: v1
data:
  token: ENC[AES256_GCM,data:x3i7cng6/t6ZW1toqs41o0sbAarA18dIaG98uet+zBehogKI9IKQAwzueGA=,iv:7fGS4/BPbkyWejBUeUGK4bYLmku0U3jZcD5uwKVd2q0=,tag:3rNwVJ5TxtNIf/YwttK62w==,type:str]
kind: Secret
metadata:
  name: gitea-ci-token
  namespace: gitea
type: Opaque
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFhBbXZpS0NK
        V3ZkNGhpVGNEdnlWZldTdWR2VG5TbnUrSEMxcDFaekFQcmFGOXpsSFFPK1IxYlNR
        TXR5ekYrY2JGRFkxWUpVT2VwcnpEVHhMbVkvU1RYOWJueWZFUnhWRW1adzJFZ2Yy
        anBtNTg4dklFV2tkakZjMzc5bWVCbmZsMXF2Q1pxdjNGdnBaQ2grZ2haYnRIUGt3
        RmFZaWE1REFwOGJGaFVTUFU0Q1ZsNkNSTm0zY1NIdUIrS1ZCN293c29mam1PTk83
        RXJJVUdNU0lsdnlJZGRkNHZQT3RSTDJ4aVh4Y3Nmcnp1RFRZYmI2YmR2SGdHL1pT
        bjlxUVYwZHN5YUc0dXU0dkVERzhDeE80eUFsbk1rMzVKMDNQKzdkRW0ycVdYUEtk
        bmg4c0Njdk9ZUTFWTmVIN3gvTDdkYlFpRU1jSmY1U3ZWbWt5Tmw3b2h1VHNqUmZu
        RFM4QW5kcmtkckJGTzNkOVlEYmJwUWdKbDI3OUx6cjgwdVNSUE5XZzBzcEhhUmRy
        T1VJRmRXNlo5Z2JQWHVPVkd3cWE4NVUwRGtNbWozMW4xTWoydTBJTXd2NHdiQUo3
        Zi8rSlJ6eDFBT3FmcnFHL2t5VmV5Tm9jbWRibTlDRTNiWVhXVkF0cFMzZm9rS2Vo
        Q0UvU1BEeWRTeVAyT1dTcXBDWC9rQ2VrR2RIYjNoaE8vK01adzZpak55aTI1cjJY
        VGoxOHpjRy9TWmR5bXNicnkxZll6UXhtdC9aamhOdFVsMFRpMGhtb2g5a0xxN3RW
        SFlMY3J3bjhNd2NkR2dENmlabEZEdnhoOUY5NFZqNGxkOHFxS2pyVUdjU1Nva3ht
        N0JLOXBHdzN3YWhTOHJPRHI5MkpoYTVnNWFDdEwwZVRpRzQ1Uk9LQnE0RlRXekpl
        TjNLSnk1eTBUVmpkVVJEdmNTOXRuSXVYaU9iWW5ZMHhpcnVCSVlxNmVLRzArMU5Q
        SStnNUNRZ1gzbVcxZDg5WFR5TGNYVXd5WWFLL3hMQ3NrK0hreDhRcU9MenNhQy81
        eVBPK0NNMXB0NktsMzQvZHhCTnpCbWRseFRibnZ4SUZHTW8zS0JPWDRFVFBNd1VZ
        QTh1Q1BiQWttdExVT2doSWpJUWVveFNXNVd2Qzg2ZDh5Z2c5cDFyNGp6eTVNUG50
        dWdDd05LSEJDSFpreWgyZnY2cHo1eC9pd1VLMGU1TllWaDQwVkNqOUhtM2RXN0JG
        MW5UVFQxTHNUOXFNcnplOWtRZFNzVU0vL29BUndwaElKMzZlZ3V5cWxyVHVHbXdm
        N2RmenNtS3dCbldSRFBRQXFtaHI0ekhoSXhRbVRyZW9sYkJZM1VXUmQrWFVUZTFa
        NlZIK3BsdE9tL1NyNTNHeHI2UEdoRk1PUUJybVJTdVNDTEtPdUhiUUk0dmxMb291
        aGpjOFA2MlVVcXZxLy9HeGdSL2MvdWZtMW9pQUp6SW5qRlNZdkl4OGtjMmNnWDll
        M2JYUmpTWll6SXpDbEdDcGpTSVc4K2lGMUtTMUJUbkZXbTBybFJUMVZ6cFE5Zktp
        Zk9qa0dpTGJqYVZ0cUplUkVGN1h6M3lKOExRZHg3clFoVkhCdmR6K055alQ5cVd1
        Rjh5MFJGcitHVVpSZ0NsS3g5WXh4eEorNUJwOHpaRHFwcGU3d3pQcmkxQTg3R2pt
        dDlIdzI2eTdkcW82ZHk5K3FYYUZkQVArNUpzYXMyZDJFQ08rQ1pRVit3REkrSVpU
        RVJhc25Dc0FPbW9OS09lYURtYlE5TjFLS3g0RFgyb3VqSHdpZ1Y5U2g0emZPbVBL
        Q3NzdktnQkdPWXFxdVZOKzc5bnFCYjRYdTJSSFNlRjJtdjA1S3lJNCt5bmNBSVIw
        S1Nkb0t6M0ZjTjI0RUFCQUM1dGp1K0ZKbDJjWUc0VjI4R0lJWElGV2htUlRPUTNE
        UzU4Y0VwOHYxbHVPMDhlNlRvQ3hrbHpQKzc0YTZ5NkxLdmFmQXdoSk5pOEFBQQpT
        ZjRFWFBneGI1QmRtbktZVEpYMGpnamNTS1FqSGtsbHZ5anFqN2l2SFZrCi0tLSB0
        UEJ3QkJiSFJ3WFlWa3p4Mmc2TmFzREpNQzk3K1U5eHNXQXFYMUI2R2drCjgAzc5D
        l43Mgsfj8mf0TbVRtqlHbxL4JJPoNSSY51XbKmOTc2zaI+e9/uryHeDuJv9bczN8
        EJft7PM+Aqe98cw=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:xvhmOOcPu0x6VJ4iyhSYyhgmEOYV6gpKQwh4/ptGEnVVPWf3jlBq9cT+Z/OAyyHPC9IMB7cbFY+yf5B+s4P6NgEVjv+5W51okHMYAx+UvBH9rmNgvlvhCudphWUF0vXnQgn2QT9Bf4Q0x7Z3V4jkq2cUOGfn1Jib9TqVGICuOaU=,iv:4TK/Hbobe2fXAevCCNul9QFMoIhadh1ZYpEvg13gMOo=,tag:7EZwMMYtYkpNJB+lpHTASw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$)
  version: 3.9.4
