name: Renovate

on:
  schedule: # Every day at midnight
    - cron: "0 0 * * *"
  push: # if renovate files changes
    branches: ["main"]
    paths:
      - .renovaterc.json
      - .github/workflows/renovate.yaml
  workflow_dispatch: # Manual triggering

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Run Renovate
        uses: renovatebot/github-action@04086b4a46c89bc2d3ba4ada1158bdf4ba2636ef
        with:
          token: ${{ secrets.RENOVATE_TOKEN }} #PAT
        env:
          RENOVATE_AUTODISCOVER: true
          RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
