apiVersion: v1
stringData:
  email: ENC[AES256_GCM,data:wSUmNQ6jYqUaAAETBGur3EuzFA==,iv:GvifZYWyPPjquCy4sZBjS1HypLYe6JyPQJ1bqtGzzPc=,tag:uZ7XWiJozvKhVjPjbAbV5w==,type:str]
  password: ENC[AES256_GCM,data:Qg80fRrfvu5cBf21BnRpDJfzVcrdnN2blqOV,iv:uGpj9Pk7bP7HoXfcUbB4Ubk5tSI57vTqyZyoqhmnevg=,tag:/6Ezz6DUfdrxV8kZdsa6Lw==,type:str]
kind: Secret
metadata:
  name: beem-exporter-secret
  namespace: watchtower
type: Opaque
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFJHQzZsMGJi
        VXJmd0xsOE9zT1VsZVdIMytFZlRRRkxPMWRLN1FOVXJieHdWaVFQTUhTSk03ZGxV
        QlFLY0xFLzRuaDhhWEpZSVhwMHlkbjJXTDN2VVp2R2dZUXNGU2pwdnd6anlDRHVR
        a3ljcUYvUGpRWmxjbFlOeCtmdHNTaHlySG8xZGpPQnVUU1VkSnd3SUhIdktCRXlQ
        bEcwbWkvQStZdHNDOFdtQUtJd1BOQjIrbVVKVGk5RGFWMUVtRlgwZTlMZUtGMXpn
        eG41NlZURUtNcW0xY2pDd0JwK1pDdlIxRzlHVXdpa0Nuc3FTbUtTOVMzdzZWSDZ2
        aGRIL09UcDB2U051N3FvSE1zZWFWRUhHS1pvTFR6TmZDaFBONHZ0Yk02bmEyY1hy
        NTVualAvelBSQkRaRUNvWEgvL3lpcEVWZ0QvdjBvR2pMdzk2VUdtZGVyTUtERGxT
        RTNXRGZEbjJmZnZFSWpXMERtV3VvVkxVNzVCZFZtN090K1NWVXhqZlFubjR1Rno5
        citsdzNSODNyak5PK0lmOXJuUHM0NVB2VGNLbllBM3k1T2Nydk9UbDVFZ3MyOTh3
        dEVKeFJJN2dvRUdDUWVkby9HcWg0SGdPcWlGMkZxMUxYNVl6TXJLVWxpUUk0dEpY
        OUdZWlAxbldtMlFtLytXNFZ2azhUQVlEdS92NnF2WDRCajhNbzJLWW9hWEhYUGFS
        V1VGbkVwNVFFcXB2U0dCSzVEQnNoaGxqdG8wRmJPMzR5c3graWNrS2hnd3JnQmx4
        ZWZnVnMzb0ZxWXV4bWxVL3VqZ0Y2T0QyMGUzdWZuVDdqaHdSNGdMRStNMEE5UkxY
        RUh4c1hwR0lWRU5FcTQzbHpWc1ZRQTJaSEdINXBPa1RBM1FHM0dyMWNjS1NTRC9O
        dTdXbzY3WFJOaFlZeUducitDbzVlaC9ISWEzRmk5U1Yyd2lxUVlhaHl0UHhaeWhm
        MHZVczh6V1IrVWVyWHpqNDFSY29mZ1RsbHU3NXJudGtWbXE3b2JGWWtwUVhTOEdD
        cy9jZ0ZTWTc3allDZUNCaEl1ZGllRUx0dTNnejdWQjI0MjFuS0NGd0FuSWFvaDdy
        MHZXcUI2bDhoL21QM0VXRlFZV1VjazdmNkc3b0M5Nm1Idm8zWklHb3pwdkl1czRD
        OGlnQmVuT3N1MERqQk5MU0U3L2ZKblhWTS8xK00vc1B5a0c5aUJpd3JxWlRGYTFi
        YjJOWkwyWkVFOWJDM3JkQ0lrSVh3UjFIdkxaRFdCQkFjSS8wb2tnb3FqOVlOVjM0
        QWpidW9PRm5jbXRUckJRR1dJc3JyWXJTUHNma1ZvNlhYbndpNTEvSTlFVjNJVEg3
        OFA0cFE0aW9Id1hRVTFjRmpUbHlPZWdhUjdURUk1TU5kYzNIY0wwRGtHZjZEbGh6
        S3JrR21HNGZEQzByUEcrNUlLck1wVFNYR0c1N0lmVzJKWnlNb0phY08wY1ducys0
        S2hQN0xlRkluMDVnOTEzbEFxS3I2blZJUFZJTjhwU1hsTTNhd01MK0NBTWk1cnZk
        SS8zTFQyTWkxbzVKRjBPTGdxTkl2Tis0dUMxOGErRjBJY2YxT0RqVklGSnMwWE00
        M3hhZU5CMnFiSFlmR0I2RDQ2bjJESTZERzBzeTB0NEF1SnhHcUM1OXFZQmV3RUdK
        c2hwdndGTzZmVkt4cjlJVWMrQ0dzZlN6V05uQ0s4eVphOUVBSThUVkllTkR2enpo
        cVR2d2M0WWdKemNObUV6M0VMQjQ1Z3JKOWc1dDlIbjFZSDEydEx6T25lUVZNQURH
        VFkwZkNmVXRiV0llelc3R29zYlRXbE9BMFhadVBldzVzWlhJejU2UmJHUVVuK1Fv
        K3JFaTR6bXdPbzhkVGVxS1lING95VnIvZ1dXcGQ3ejRLSFRwRzB1OUs1dnp1S0N6
        NWNYaEluVldKNDFQUXg4Vm52QUUvK1ZYNU1jMTd0OGd2eUtERGlhYUhNTS9kQQph
        bm8wN2ZKSXh5cDRjZzBLWFBkdzZZUWljeGJhYlA2NmdwLzRTbW9PZFRRCi0tLSBM
        VG8wSmJLL2pmYUg0a2p0MnZ1SFJncHFZYkZiQTlRY1p2dkE0SFE4NDk0CoOlr0dG
        kebdZGwr4KB+li84VUWC+VwhW/rtvMeV2gtmM+pEg+ZKABW3nq5OZeD8EpdaSuxu
        wjm++xaiQeAndXM=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:48:22Z"
  mac: ENC[AES256_GCM,data:6938IwQlDKtGUdzZmpSNUn8iE9NRxgj1EI/B4kY7+SOus3WPj+2VoVrmeSa8xHi0KMjmKLsBtzbvjWBseD6NHOnC2koajH95d5hIkq306gRi354nc1g9CyjBiVhkcEwsHSDoVuJChnrCtqlHvhqjpO82rKqI9S+qMah078dSmfo=,iv:6U3FBUzK8MrbEzD2Afh08MbizjQAAmMGH8khbL2SFmw=,tag:7lmRq+7IvynWjFl8W+Stxw==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$)
  version: 3.9.4
