apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 10m
  chart:
    spec:
      chart: appchart
      version: "1.8.0"
      sourceRef:
        kind: HelmRepository
        name: appchart
        namespace: flux-system
      interval: 10m
  values:
    apps:
      - name: loki
        image: grafana/loki:3.6.7@sha256:3c8fd3570dd9219951a60d3f919c7f31923d10baee578b77bc26c4a0b32d092d
        containerSpec:
          args:
            - -config.file=/etc/loki/local-config.yaml
            - -querier.parallelise-shardable-queries=false
            - -reporting.enabled=false
        volumeMounts:
          - name: loki-data
            mountPath: /loki
        volumes:
          - name: loki-data
            persistentVolumeClaim:
              claimName: loki-data
        service: 3100
        pvc:
          - loki-data
