apiVersion: v1
kind: Secret
metadata:
  name: prom-config
stringData:
  values.yaml: ENC[AES256_GCM,data:HuwHWCdjyp7uUSojrkpfknnOhGEvU8fx3ta0z/9Iix7/QxoVWCm4wQNcGztUAQMbZazexMrOh9vgoNO3jNJxWlz9sFsPl/nxi++g/NcfnZWYhbg3TMRcAfAINCqp+b0v9fDPASMytywJJqjcnMk0eCEFiJAI7fbfbSCbpWGrlCcaPX61EhWZNpbx+qeAJHkIXGzh93dMVOP7CbOSKU2RNOVf1XgyyHnUarYoUh59u+Kum81j+UkPHfFCrfs1NMXBs/YlQ30eT5tmV1L6M3szMt4AFhuNqzM+uKKhZKrRHCX/qNY9dWCrZuY4Emzq67YSChHebKpCDuOgYVJGOevC7dnyNZF2NqMF8z5TTy+tCqip9TZ44O/add17mqt3ZgxfpJzcFQ7qEegjncCj+pIA0T+2bFx/eYCtQYukm8nc6SKokT2l93+G09GIaFP3V5nqEP9pNNSyzngzU+Z/7R7GFBzLkaxpBZrsq4Q2SnHxyl6Z0x6zgC6rHgJLHrSFQZ3bEKacDohpjSCUAhNdumWutWYzMKPMGU3Rf6GyaI9+ZOKgrrJp/BuDotGx8DjGdhkyA7GxZRDz+Zk/PNQ0VP3owm2NaLaplA7+nX/iuQpz84xXMBlv8w3MrWo/zJDB5zpYUKlUFy1516Pu1kTSmb4+p7ZwQwTkSLbI6kYG+VwyNqlfwxhkmVGagG5CIZtnFDYGz0rOoU29X83pr5k8WoVA61JMr8pDUv0NPT/72MPY5LKler0aaJCFNWcWUjifFcnwyRzEzZZmItYyiZ9D+i3cmNy47GXpbOu6EKKGDQINWYw=,iv:FqweV6+I+xNmJowhbxhgiy/a7oGGT6S49AZYuysPiP4=,tag:4Tx2YE3nGAHG7oR/VCVn1Q==,type:str]
sops:
  age:
    - recipient: age16xc3m2q69s2le4hah3pcne50qn6mljhgc9mxekskwf0mp8fc0vaq5q5dz2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvNnBPNTZleTZGLzdOd29F
        VWdUeFBPRFdpYzFWSjBGU3pMV3VpQ2FKUG5JCklrbmxEYnFSdVNBZ3hFS2dGNUxC
        T1AzemxGSU5jMTl1bWx1bkpvZ0VRZEUKLS0tIER3UjlqTnlWNWc1K012aldUVEVI
        UE1KT1BEc0c5L2tNQVBlRVBsVlBDTjQKh33j1yOzEmpI24EKDHgJOoFIyKXgLC6u
        eIBxuRjfNLexjQ90M/QoRSwIKr1lQ2ZB01/oiYdgta5WR1IB4FkU+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-11T21:14:32Z"
  mac: ENC[AES256_GCM,data:vJrHcj8mKXqLe0IooxiE7q+ofCQHWRdFMDP1mv7HN6jYHQ9sfvtfzTGTF8i41aNtxDAYprlkCJIcV2mbDwWei4RTdbdK+HNkDtN8Hn5xFbMoZprHZSfdqKoStuirQlOmnOJMczlnzy+5LsIbDDBzAaVUedA74Xp98dNHyks4Dfw=,iv:0pQE6qVjplk8Tm3JXypDqS/rhNAw6loqxcvnrza2RSU=,tag:ThnffwPg7RPf8vGTP7Au5A==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.1
