apiVersion: v1
kind: Secret
metadata:
  name: prom-config
stringData:
  values.yaml: ENC[AES256_GCM,data:4SJMizSD5fxy+8Mx2QmqFrbTcAGQZPx0pGXBZhNKR8IhjjFMyA3JY8ACtYImCkhYi/ZaDRSLmtZIEG4BiSIsJcWcIgKrcuct5QgxjzRuWKnDLk094Z64Zcwjavue3jg4JY6q/6c/yaC3ieAmR0AarXMBth0xgL+kzsu/W/rr9uVKIHS84W6amPHGHDbywMeSMrAsWOnlCW6DCplwX4M1IsTZW36YFisolrRidYfZmycsb8x+IVHL7YF3i1saGbJ7Nr7jbHECpZU8NO453AIA+p/piMNCV9HwwUULFxWYZVWzqAfcyeuWvDydevxQ5JX7onw5Awi2kQ38+sgmxRt/N7i+dYoZUQetJ2Nj639R05TKZzboXkJZxM3xw5daBt6FUi34XHTO/Ssur3aUt4EPuGaGkINFr4MYFJpm6YgeGfKIwioV1ePPEhzEibOPNrKhoKooZo+VlSZ3wI09cNccVgRlPDiucszaSsNimfbBZn2BJYt/FSZIUr1jGB+hZZ1ZDGw7ivg3CelP1YoZTERSFgbWylVHlo1IZEuYKiJyE7ev1gpNE34P7mCl+tFDuUlo339GeGEAkEtrltwT/BjBje4dzQ/GZofGExwZrwivAAZRckXMPX6HTynLfZdw/CcvNkrU3IWwex5al08sccWS56eSD8AAIkVoTupvoUc+s9ScdMzVUemT+vjjquD6CtQBTPy+CVkIe1pMXERNxtTSn7cC50Ftg21XiLcbC3REFfxHk/NyYdAO2LIlyXburaKG8d1LShQDBsxsmWH3FjEZDc9WiLKheer7wq7Gx+483aA=,iv:FqweV6+I+xNmJowhbxhgiy/a7oGGT6S49AZYuysPiP4=,tag:TekajD/X8UycbpxSpauyYg==,type:str]
sops:
  age:
    - recipient: age1pq1zu5fgd0qzk02p0g5mdl9tvswq0amuy75280fc9mfzvtgsl90t0axzrjr9zv8x64efg355zdp02zzpyzpzmtp4p7dw64etgereu9qsahc52wfyqurcf8cmxett5ngs6fcg6775gsvzyp9thy4gw9eduagk2pdh84wapus946m4a69v8yc0nxe5d8c82vszqru6z2tutekjt5qnv8duya6kve8v079lhq9q0layzgj2kp2qkvvsrz65aauv3nvy2aydfkjkyyx3gacl7ec9fgfv7nnyxhddfr6tkayyd0p99hej4j30jtzxdclgucsv94gx7d35pldkfynrgdv2lxq3a0tfs37wtzzmsrq03vt9ysh3ntmf44q4wf88xqppc6t9pjs5auudhxd0ffgjd5qyw3e6pn5c02xttkxvttludkcesj5dhmzj3835ecg9yjemvx7flzseg5xmfzgkzduwd0say5s6nyhf7ngp6x63c8fh0expvdc0rrcypek0huqgc6u5ntcwhqh34c3kpqvxw7mfwlj2rpnu7zw3xk207qfsfvmhxxqk57ppg9lz4uvffppxr7qj64c9rwt2gzk9d40kqgmkeeg0qgkwx05xse59tqtexfjal0unf0qvrm9cy6tv76w2uruf935hs9rzynhpnpsjd5z5hntna7x88dpxyrkevagmzthvsn5hqpvcq47dnmxks0qzsaduwcxcmg5n8x4zvq7zek0g4kxlsqhpnv39nrjgyl5gknlvyvcff6r4qk8zp5ppf9tz4sv757t6rtvrvugg5w98dgtc7ccv4zu8pufqq2jkj8jwyngwygc5hy958npfj9rcajw80fgmj0py2j6k2nn55fcselfvn7lky5xu7e0m099g5tfy3654y4lvx6mcqwr6vr336sg5d05896vjy62x43ur95nyql4t2ng5akthtqd8xdzlnmyjtyeq2tpsn3pcmxd823pel5xysykj3v9v7cv3yhw7zqnzn6nwsptje06ffv7j9uqm5adzauk6gsuczjn9y8gczc5lj3tm5mvl5lzwpk3z47chscpmy570cy2spx90u8mnpz4axk0pvupxettqtg3sewh928xyh95fzg29ks4x47zxt2lfz3jm30wt5zk9uytx3mqy72s0j3h3fnh87g3r06pyr5cz29242cr2zc5v3mxhha5xdcp3rpr2nezwqsflsvymr2hkdu80jvxdzrdyq5cjw9qshsgrfaewvq9nzfeax48e5ja9xynmz4tfwxlzx47xrqmlg3lfrsn94k2d2wg42gfuk4agqcs0h6tpskyxyhrszkx7507e5fadvccm8uq5pf9djvl6q7khyrnxtfusqfkhydw2wes59fupyu4fqtj09zhr2spv5t825ykmrpnyaptjttg8w79qzg4g9xyp7nlk6q3e0m5eulqxmqnz6la7fvpu0y36yfczntt22dq9zey3cne3pdf353edxhe2hwzxxt9dxe727ug9fu2raml0y3mzvupv6gtzvgjq23hqc4j2gcqfwwd9k255cqj84t4t6k2wkc5gvv8qpcwxpvkw509e7htz3j2smykzfgn7pw9zzegrgdjctyjct9d4u5jv336nfg4np6ggd5r6xnt96dnzxmsl6h3f3p9ky0z77xlscy0qx2hygr8zqedkjrcqerghpca89arvmvn2jgpew2lu4ny4ypqj43n3ahf5emjndl5yzm3msjz74ynfwtghc6f0t67tfqnkeuy9mvfvwaerdl08dg8yqllz6jrtw3gxpdjrdccfg090vz4hdyk2dasautu0x2uqumskjmt0rfu77ktdsg7lqw5sc7e400a0xtclqtydeptdqyfs673es6v0c0vhq2z4eehzt07msjqvm6rfy6rcmll7vvea620z8y27euymw9kws49wqca
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFBVOTUzU2o4
        ekUxb0ZkZk96ajNrWWZCVGI3NVdCMTU3R0VEYk4yM0dJWEpKTDNqczVwNStqNDlx
        b0JHZkJ1QlpiSm1UUzQxcDcwZnhqOWNMM1NSUlZTVWJ6UG9XYjJiMFp6aTBleGVF
        ek1PaUlFWXlEc2JhL2Y5OThObnRLZDNRQ1dHR2V0ckNkam53OXJHcTVaR2lmc01W
        Q3NHL3NXNkFLT1N3U21Sb1NRbWFtdHdCUnhsbUowK1dQTkMzcGlTZkVCbHUrQlY3
        ZnZOaGF4MmIvWTdjNklKVHk2Q0JGQXVOQ0xxbTdNUjJjVGtLcnhtUmdKeFpaaXR0
        TGIxSzZsbUxxTXFZemQwcklLYVZvK2ZKb0drcUUveWxEMmlxcWJaYit1SzZkSFFR
        V0VGQkVMNzdYMG9Gc3ZFcTBSb1hZVEx6STM5T3djQ1VxcnYxSUMzWStWN1ZDV0JT
        MHJPMENPc0V0OHZ3Nmd1Y0JIUElZL0RUYmVuTG5RUHpOZmlrbkN6YTFDcFZ2b2x4
        aHFVVXNTV3BaSUJWdlRCRkliQWhmbjBYRXViT29EbWpYSWJoRVNJak1CejJvTzFa
        MU1tQTRIbEFRMWhPRjEwa21nWnduRlhSN0ZrVFkzK3B2T2NaUHBWMlB1VHArd0Jq
        R0llRHBUUnBmbWU1NmVUbFpBNUFRMkxHbnZOU3l4V2ZUcGF2WCtvNWhDQ2dGcEgr
        Mlh3Y2FuUnk3bTkvZjRYWmFMWVVua2JONWtRUytsUFA4WlBnb2p0M0s4WEp4VnF2
        UXc4TjY1WHpqeXFyVFJHcVR3cmdDV2xBVVhXSlppbkhkc3kyd3dpanRBNWJIWEdS
        V0FsQ2FobWZaTHRsYWJoaTdLeG1zWmlpYVI1M0NIMk9ZWi9GcXY3bHpXalF0am5p
        Ymg1ZkRoU1UrcG5lZUFOT3Rlc3YzRDhYaHBsTWNBUHFkbTJJKytBUXY1YnRNWE01
        MVJtdjEySjlMaEVtM255U21lakptWXV1ZnhSZ1NTbGh3Z1YvS0RDV2lHZW54dlhq
        ekJMd0hrUjd2TjBVZ2N4TW9xL2FpU2FIaXRveHNvY2hWd05jaDljYTBENmdiQnJ4
        dnliNE1uajNrcUwvdTEvdFRONkU0c04wbzdBNy9lUlBaaHV4bUQ0T0NyQkJhNnZI
        QWo5TWRidjR5cjJxOWNrM1BvUFhwN0hWWE80RnVvUXVuaWJDakQyVEFFMFZzMkdu
        R3p6MVMrVWdtTitES1VqY1BkTGQ2WkVCaGRocktoRDJxWWFNblZkSjhPWUtLcTJh
        S01XeVQ0MWVNa3FBblVTM09XYmwzVm5JSXgxRkZSR2hpK2lVR0gwb1ZCbUZxanUr
        SGpTVGpnRlowTFVQTE1IWVI0NVorVEt3VDdpeFBSOUt1K0NKUjNMSkZ5UGZEUktB
        cmp2KytNb2RaNkRaNFdqeTRQZjZnbmlEL2ZaYlFQMzhuTVZqaWpRUmpadlAyNE9h
        bWE0ak9UOE1pYzRTM1RqMU5ENTRCTHNsUDM4KzBNT092VmlaS0VBSnRIWnJvMk1Z
        VFVMOWNFbE5LbnpTMS9DSEkrZGtMUmpzcGw0VWNaOEJRWnRDbE5XSE0zeXZ0MDJJ
        R2w1Y091V0pjcUxRSklkL01tZGQ5czU1UmFPekIyR0N2a0xJaGpLb2VHTWROVzhE
        b3YvOWNWMFcvZXpUd2JTaWhHbnd6MW5NM0EvUUFKbmtKeksrVll3Sm5oeE1ocVJB
        MmlYUElHVDlpOHdBWUdUZXFuZEV3SHV3VlRHdlN4dytQRWxZY1IyVDhtNTRwYmlR
        MDFXUXBWQWhPdlRqQ3h5ZHY4bXpEcjYvZ3IzNkRlLzdneGZCcWlseWZ6cVFGS2Ri
        NE1TcDVsdzRCMnpXUkRHakpERVJvd3BjdjdrbDJZZzVEV1lPbjRoc0o5THBXWGpx
        aWQxb1JzSjB0RnFMQ1A4SlZZRUk5V1ZXb2QzZHRkcmxlbEtpdnYyMXdsSXNDZwor
        K3ZwZEtKWXNzbWF0aTFYZDc5VVFSNXhic1Bjb3hKNlV3RFVldVk1QUlRCi0tLSA4
        bkVxZ0MyckJEeHZCc3dTK0ZLaEc3OUJ6RUNMSVllaG9iYWQ4bXRES0pNCqNkSdbP
        dhJvHVcIkievpaWe8AhSwR3FkB6JBUyLAVDvn2O8j+GvIjEbcT3Gku8jIj1LnQgx
        WmEEDO0ttJ+qD9c=
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:50:49Z"
  mac: ENC[AES256_GCM,data:lGwEzkNgjoS4eliGzKJ80QmkgWVqlVpPWywAcj+UmNsa9CULrTjY8wyi/dU+yHBQJpVbUdBAgclg5IbbYWwkQhPBREeQr4/tc0Ety1ATjKoBXwCjTLUOtugDfz3dPW9/+Py+5SoieBiCkaP3Un7UHR6UnUZFNZEr+5k36EqhFZw=,iv:XDaMzvwObo+VIJ93NfHZyV/HzvGDBmlS5s65F2BfxXU=,tag:BRhWelC21sI/imWortWu3g==,type:str]
  encrypted_regex: (token|email|^data$|^stringData$|webhook$|creds$|secrets$)
  version: 3.12.1
